#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Figure 7: EP − EPALL Dynamical Composites — EPALL-Relative Anomaly (3×3 Layout)

Publication-ready figure isolating the dynamical structure that distinguishes
each Energy Pattern (EP1, EP2, EP3) from a generic intensifying extratropical
cyclone (EPALL = all cyclones combined). Each column shows EP_composite − EPALL,
so only fields that exceed the "average" intensifying cyclone are highlighted.

Layout:
  Columns : EP1 − EPALL  |  EP2 − EPALL  |  EP3 − EPALL
  ─────────────────────────────────────────────────────────────────────
  Row 1   Upper-level / baroclinic structure departure
            Shading  : (PV@200) − EPALL                [PVU]
            Contours : (EGR) − EPALL                   [day⁻¹]
                       positive = solid firebrick, negative = dashed steelblue
            Thin ctr : SLP total (EP composite)        [hPa]
  ─────────────────────────────────────────────────────────────────────
  Row 2   Low-level frontal / thermal structure departure
            Shading  : (PV@850) − EPALL                [PVU]
            Contours : (T-adv@850) − EPALL             [K h⁻¹]
                       negative = dashed steelblue, positive = solid firebrick
            Vectors  : (u, v)_850 − EPALL wind         [m s⁻¹]
  ─────────────────────────────────────────────────────────────────────
  Row 3   Jet-level energetics departure + barotropic favorability
            Shading  : AFC@250 − EPALL                 [W m⁻²]
            Contours : (KE-adv@250) − EPALL            [m² s⁻³]
                       negative = dashed steelblue, positive = solid firebrick
            Vectors  : (u, v)_250 − EPALL wind         [m s⁻¹]
            Hatching : RK meridional sign-reversal mask
                       (from TOTAL EP composite, not EPALL-relative —
                        RK = β − ∂²ū/∂y² is a background-flow diagnostic)

────────────────────────────────────────────────────────────────────────────
DOCUMENTATION MAINTENANCE
────────────────────────────────────────────────────────────────────────────
Every time you modify fields, layout, or display units in this script, you
MUST also update the following companion documents:
  1. scripts/main/README.md          — Figure 7 panel table + key design bullets
  2. scripts/main/SCIENTIFIC_NOTES.md — §8.3–8.6 (per-row and colormap descriptions)

Checklist for additions:
  [ ] Add new variable to Layout block in this docstring (rows / thin ctr section)
  [ ] Add variable to compute_epall_relative() data dict
  [ ] Add config param (STEP/CAP if contour, or colormap) to CONFIGURABLE PARAMETERS
  [ ] Add contour / overlay block to create_figure() in the correct ROW section
  [ ] Update README.md table row(s) and key design bullets
  [ ] Update SCIENTIFIC_NOTES.md §8.x with physical description + sign convention
────────────────────────────────────────────────────────────────────────────

Rationale for EPALL-relative approach:
  Subtracting the full-population (EPALL) composite removes the dynamical
  signature common to all intensifying South Atlantic extratropical cyclones.
  The residual field isolates what is dynamically distinctive about each Energy
  Pattern — i.e., why EP1 cyclones differ from EP2 and EP3 cyclones — rather
  than showing features shared by the entire population.

Hatching definition — RK meridional sign-reversal mask:
  For each grid point (i, j), the mask is True when rk_criterion_250 contains
  both strictly positive and strictly negative values within a
  ±RK_HATCH_HALF_WINDOW-point meridional neighborhood:

      mask[i,j] = True  iff
          min(rk[i-w : i+w+1, j]) < 0  AND  max(rk[i-w : i+w+1, j]) > 0
      where w = RK_HATCH_HALF_WINDOW (default 1 → 3-point / 0.5° window)

  Uses the TOTAL EP composite (not EPALL-relative) because RK = β − ∂²ū/∂y²
  is a property of the background flow; subtracting EPALL from ∂η/∂y would
  produce a physically meaningless field.

Data source:
  data/era5_ep_structure/precomputed_composites_ep1.nc
  data/era5_ep_structure/precomputed_composites_ep2.nc
  data/era5_ep_structure/precomputed_composites_ep3.nc
  data/era5_ep_structure/precomputed_composites_epall.nc
  Generated by: scripts/ep_structure_analysis/step3_precompute_composites.py

Outputs:
  figures/main/7_dynamical_composites_epall_relative.png  (300 DPI)

Author: Danilo Couto de Souza
Date: April 2026
"""

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(BASE_DIR))

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import xarray as xr
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import gridspec
from matplotlib.patches import Rectangle

from scripts.utils.colormaps import CMAP_PV_ANOM, CMAP_AFC

# ============================================================================
# CONFIGURABLE PARAMETERS  (change here — not buried in plotting code)
# ============================================================================

DPI = 300
FIGSIZE = (13, 12)

# ── Input data ───────────────────────────────────────────────────────────────
DATA_DIR = BASE_DIR / 'data' / 'era5_ep_structure'
COMPOSITE_FILES = {
    'EP1'  : DATA_DIR / 'precomputed_composites_ep1.nc',
    'EP2'  : DATA_DIR / 'precomputed_composites_ep2.nc',
    'EP3'  : DATA_DIR / 'precomputed_composites_ep3.nc',
    'EPALL': DATA_DIR / 'precomputed_composites_epall.nc',
}

# ── Output ───────────────────────────────────────────────────────────────────
FIGURES_DIR = BASE_DIR / 'figures' / 'main'
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PNG = FIGURES_DIR / '7_dynamical_composites_epall_relative.png'

# ── Unit conversions ─────────────────────────────────────────────────────────
PV_SCALE    = 1e6      # K m² kg⁻¹ s⁻¹ (SI)  →  PVU
ADV_T_SCALE = 3600.0   # K s⁻¹               →  K h⁻¹
SLP_SCALE   = 1e-2     # Pa                  →  hPa

# ── Row 1: EGR − EPALL contour levels [day⁻¹] ────────────────────────────────
# Positive: solid black (EP more unstable than EPALL)
# Negative: dashed gray (EP less unstable than EPALL)
EGR_EPALL_POS_LEVELS = np.array([0.03, 0.06, 0.09, 0.12])
EGR_EPALL_NEG_LEVELS = np.array([-0.12, -0.09, -0.06, -0.03])

# ── Row 2: T-adv − EPALL contour levels [K h⁻¹] ─────────────────────────────
TADV_EPALL_STEP = 0.050   # contour interval [K h⁻¹]
TADV_EPALL_CAP  = 0.20    # maximum level [K h⁻¹]

# ── Row 3: KE-adv − EPALL contour levels [m² s⁻³] ───────────────────────────
# thin contours: steelblue dashed (neg) / firebrick solid (pos)
KEADV_EPALL_STEP = 0.005   # contour interval [m² s⁻³]
KEADV_EPALL_CAP  = 0.010   # maximum level [m² s⁻³]

# ── SLP contour interval [hPa] ───────────────────────────────────────────────
SLP_INTERVAL = 2.0

# ── Wind vectors (EPALL-relative anomaly winds; magnitudes ~1–5 m/s) ─────────
VECTOR_SKIP      = 16
VECTOR_WIDTH     = 0.009   # shaft width (fraction of axes width); increase → thicker
# 250 hPa anomaly wind
VECTOR_SCALE_250 = 75
QUIVER_KEY_U_250 = 5.0    # reference vector [m s⁻¹]
# 850 hPa anomaly wind
VECTOR_SCALE_850 = 40
QUIVER_KEY_U_850 = 5.0    # reference vector [m s⁻¹]

# ── RK meridional sign-reversal hatching ─────────────────────────────────────
# half_window=1 → 3-point (0.5°) meridional neighbourhood
RK_HATCH_HALF_WINDOW = 1
HATCH_PATTERN = '///'   # forward-slash hatching, medium density
HATCH_COLOR   = 'dimgray'
HATCH_LW      = 0.7     # linewidth inside the hatch fill

# ── Colormaps (custom diverging, from scripts/utils/colormaps.py) ─────────────
CMAP_PV200_ANOM = CMAP_PV_ANOM   # PV@200 anom: warm/cool diverging
CMAP_PV850_ANOM = CMAP_PV_ANOM   # PV@850 anom: warm/cool diverging
# CMAP_AFC is imported directly from scripts.utils.colormaps (= CMAP_PV_ANOM)

# ── Font sizes (consistent with Figure 7 and project convention) ─────────────
BASE_FONTSIZE       = 11
PANEL_TITLESIZE     = 12
TICK_LABELSIZE      = 9
CBAR_LABELSIZE      = 9
ANNOTATION_FONTSIZE = 12

# Apply globally
plt.rcParams.update({
    'font.size':         BASE_FONTSIZE,
    'axes.labelsize':    BASE_FONTSIZE,
    'axes.titlesize':    PANEL_TITLESIZE,
    'xtick.labelsize':   TICK_LABELSIZE,
    'ytick.labelsize':   TICK_LABELSIZE,
    'legend.fontsize':   TICK_LABELSIZE,
    'figure.dpi':        100,
    'savefig.dpi':       DPI,
    'savefig.bbox':      'tight',
    'axes.grid':         False,
    'font.family':       'sans-serif',
})

PANEL_LABELS = [
    ['(a)', '(b)', '(c)'],
    ['(d)', '(e)', '(f)'],
    ['(g)', '(h)', '(i)'],
]


# ============================================================================
# DATA LOADING
# ============================================================================

def load_raw_composites():
    """Load all four EP composite files as xr.Datasets."""
    datasets = {}
    for ep, f in COMPOSITE_FILES.items():
        if not f.exists():
            raise FileNotFoundError(
                f"Composite file not found: {f}\n"
                "Run scripts/ep_structure_analysis/step3_precompute_composites.py first."
            )
        print(f"  Loading {f.name} ...", flush=True)
        mb = f.stat().st_size / 1024 ** 2
        datasets[ep] = xr.open_dataset(f)
        print(f"    {ep}: {mb:.1f} MB, n_cases={datasets[ep].attrs.get('n_cases', '?')}")
    return datasets


def compute_epall_relative(raw, ep):
    """
    Compute EP − EPALL difference fields and return display-unit data dict.

    Fields for shading and wind: EP_composite − EPALL_composite.
    The RK criterion uses the TOTAL EP composite (not EPALL-relative).
    SLP uses the TOTAL EP composite for spatial reference.

    Parameters
    ----------
    raw : dict  {ep_label: xr.Dataset}
    ep  : str   'EP1', 'EP2', or 'EP3'

    Returns
    -------
    dict with all 2-D fields in display units, ready for plotting.
    """
    ds_ep    = raw[ep]
    ds_epall = raw['EPALL']

    x    = ds_ep['x'].values
    y    = ds_ep['y'].values
    x_2d, y_2d = np.meshgrid(x, y)

    def _req(ds, var):
        if var not in ds:
            raise KeyError(
                f"'{var}' not found in {ep} composite.\n"
                f"Available: {sorted(ds.data_vars)}"
            )
        return ds[var].values.copy()

    def _diff(var):
        """Return (EP − EPALL).values for a named variable."""
        return _req(ds_ep, var) - _req(ds_epall, var)

    def _diff_opt(var):
        """Return (EP − EPALL).values if var exists in both files, else None."""
        if var not in ds_ep or var not in ds_epall:
            return None
        return ds_ep[var].values.copy() - ds_epall[var].values.copy()

    data = {
        # PV@200 − EPALL:  SI → PVU
        'pv_200_mep'    : _diff('pv_200_anom') * PV_SCALE,
        # PV@850 − EPALL:  SI → PVU
        'pv_850_mep'    : _diff('pv_850_anom') * PV_SCALE,
        # EGR − EPALL:     day⁻¹ (no conversion)
        'egr_mep'       : _diff('egr'),
        # T-adv − EPALL:   K s⁻¹ → K h⁻¹
        'adv_T_850_mep' : _diff('adv_T_850') * ADV_T_SCALE,
        # AFC − EPALL:     W m⁻² (no conversion)
        'afc_250_mep'     : _diff('afc_250'),
        # KE-adv − EPALL:  m² s⁻³ (no conversion)
        'ke_adv_250_mep'  : _diff('ke_adv_250'),
        # Wind − EPALL:    m s⁻¹ (no conversion)
        'u_250_mep'       : _diff('u_250'),
        'v_250_mep'       : _diff('v_250'),
        'u_850_mep'       : _diff('u_850'),
        'v_850_mep'       : _diff('v_850'),
        # RK criterion: TOTAL EP composite (NOT EPALL-relative)
        'rk_criterion'    : _req(ds_ep, 'rk_criterion_250'),
        # SLP anomaly (EP − EPALL), Pa → hPa — used in row 0 only
        'msl_anom_hpa'    : _diff('msl') * SLP_SCALE,
        # SLP total: EP composite, Pa → hPa
        'msl_hpa'         : _req(ds_ep, 'msl') * SLP_SCALE,
        # Grid
        'x'      : x,
        'y'      : y,
        'x_2d'   : x_2d,
        'y_2d'   : y_2d,
        'n_cases': int(ds_ep.attrs.get('n_cases', 0)),
    }
    return data


# ============================================================================
# HATCHING MASK: RK MERIDIONAL SIGN-REVERSAL
# ============================================================================

def meridional_sign_reversal_mask(field, half_window=1):
    """
    Boolean mask: True where the field has a meridional sign reversal within
    a ±half_window-point neighbourhood along the y (latitude) axis.

    Definition
    ----------
    For each point (i, j):

        mask[i, j] = True  iff
            nanmin( field[i-w : i+w+1, j] ) < 0
            AND
            nanmax( field[i-w : i+w+1, j] ) > 0

        where w = half_window.

    Boundary treatment: the window is truncated at the domain edges
    (no wrap-around); nan values are ignored by nanmin/nanmax.
    Zero values (rk ≡ 0 exactly) are NOT considered sign reversals
    (strict inequalities).

    Physical justification (applied to rk_criterion_250 = ∂η/∂y @ 250 hPa):
      The Rayleigh-Kuo necessary condition for barotropic instability
      requires ∂η/∂y to change sign somewhere in the meridional domain
      (Rayleigh 1880; Kuo 1949; Charney & Stern 1962).  This mask
      identifies the zero-crossing *band* of ∂η/∂y along y, i.e., the
      transition zone between positive and negative ∂η/∂y.  Hatching this
      region highlights where the necessary condition is *locally* met —
      not merely where rk < 0 point-by-point.

    Parameters
    ----------
    field : np.ndarray, shape (ny, nx)
    half_window : int ≥ 1

    Returns
    -------
    mask : np.ndarray of bool, shape (ny, nx)
    """
    ny, nx = field.shape
    mask = np.zeros((ny, nx), dtype=bool)
    for i in range(ny):
        i0 = max(0, i - half_window)
        i1 = min(ny, i + half_window + 1)
        window  = field[i0:i1, :]
        col_min = np.nanmin(window, axis=0)
        col_max = np.nanmax(window, axis=0)
        mask[i, :] = (col_min < 0.0) & (col_max > 0.0)
    return mask


# ============================================================================
# AXIS HELPERS
# ============================================================================

def _ax_setup(ax, x, y, show_xlabels=False, show_ylabels=False):
    """Square axes with storm-relative extent, no tick labels by default."""
    ax.set_xlim(x.min(), x.max())
    ax.set_ylim(y.min(), y.max())
    try:
        ax.set_box_aspect(1)
    except AttributeError:
        ax.set_aspect('equal')
    ax.tick_params(length=3)
    if show_xlabels:
        xticks = np.arange(-15, 16, 5)
        ax.set_xticks(xticks)
        ax.set_xticklabels([f'{v:+d}°' for v in xticks],
                            fontsize=TICK_LABELSIZE - 1)
    else:
        ax.set_xticklabels([])
    if show_ylabels:
        yticks = np.arange(-15, 16, 5)
        ax.set_yticks(yticks)
        ax.set_yticklabels([f'{v:+d}°' for v in yticks],
                            fontsize=TICK_LABELSIZE - 1)
    else:
        ax.set_yticklabels([])


def _add_slp_contours(ax, x_2d, y_2d, msl_hpa):
    """
    Thin, semi-transparent SLP contours at SLP_INTERVAL spacing.
    Serve as spatial reference for cyclone position — not a primary element.
    """
    slp_min = np.floor(np.nanmin(msl_hpa) / SLP_INTERVAL) * SLP_INTERVAL
    slp_max = np.ceil(np.nanmax(msl_hpa)  / SLP_INTERVAL) * SLP_INTERVAL
    levels = np.arange(slp_min, slp_max + SLP_INTERVAL, SLP_INTERVAL)
    if len(levels) > 1:
        ax.contour(x_2d, y_2d, msl_hpa, levels=levels,
                   colors='k', linewidths=0.45, alpha=0.40, zorder=4)


def _add_wind_vectors(ax, x_2d, y_2d, u, v, scale, key_u,
                      add_key=False, color='k', alpha=0.7):
    """
    Subsampled wind vector overlay.

    Parameters
    ----------
    add_key : bool   draw quiver key in top-right corner of panel
    color   : str    matplotlib colour string (default 'k' for anomaly winds)
    alpha   : float  transparency
    """
    sk = VECTOR_SKIP
    Q = ax.quiver(
        x_2d[::sk, ::sk], y_2d[::sk, ::sk],
        u[::sk, ::sk], v[::sk, ::sk],
        scale=scale, width=VECTOR_WIDTH, color=color, alpha=alpha,
        headwidth=3, headlength=4, headaxislength=3.5,
        zorder=8,
    )
    if add_key:
        ax.quiverkey(Q, X=0.97, Y=0.95, U=key_u,
                     label=f'{key_u:.0f} m s$^{{-1}}$',
                     labelpos='W', fontproperties={'size': 13}, zorder=12)
    return Q


def _add_lec_box(ax):
    """
    Dashed 15°×15° rectangle centred at (0, 0) representing the LEC
    computation domain used to derive energy conversion terms.
    """
    rect = Rectangle((-7.5, -7.5), 15.0, 15.0,
                     linewidth=1.2, edgecolor='k', facecolor='none',
                     linestyle='--', zorder=9)
    ax.add_patch(rect)


def _mark_center(ax):
    """Cyclone-centre marker at (0, 0)."""
    ax.plot(0, 0, 'k*', markersize=12,
            markeredgecolor='white', markeredgewidth=1.2, zorder=10)


def _panel_label(ax, label):
    """Bold panel label (e.g., '(a)') at upper-left corner."""
    ax.text(0.01, 0.98, label,
            transform=ax.transAxes,
            fontsize=ANNOTATION_FONTSIZE, fontweight='bold',
            ha='left', va='top', zorder=11)


def _add_colorbar(fig, gs_cell, im, label):
    """Add a right-side colorbar in the dedicated GridSpec column."""
    cax = fig.add_subplot(gs_cell)
    cb  = plt.colorbar(im, cax=cax)
    cb.set_label(label, fontsize=CBAR_LABELSIZE)
    cb.ax.tick_params(labelsize=CBAR_LABELSIZE)
    cax.yaxis.set_ticks_position('right')
    return cb


# ============================================================================
# FIGURE CREATION
# ============================================================================

def create_figure(ep_data, output_png):
    """
    Create Figure 7: 3×3 EPALL-relative dynamical composites.

    Colormap limits are computed globally across EP1, EP2, EP3 (98th percentile
    of absolute values), so shading intensity is directly comparable between columns.

    Parameters
    ----------
    ep_data    : dict {'EP1': data_dict, 'EP2': data_dict, 'EP3': data_dict}
    output_png : Path
    """
    eps = ['EP1', 'EP2', 'EP3']

    # ── Global symmetric colormap limits (98th-pct abs value across all 3 EPs) ─
    def _sym_lim(key, pct=98):
        return np.nanpercentile(
            np.abs(np.concatenate([ep_data[ep][key].ravel() for ep in eps])), pct
        )

    lim_pv200 = _sym_lim('pv_200_mep')
    lim_pv850 = _sym_lim('pv_850_mep')
    lim_afc   = _sym_lim('afc_250_mep')

    levels_pv200 = np.linspace(-lim_pv200, lim_pv200, 21)
    levels_pv850 = np.linspace(-lim_pv850, lim_pv850, 21)
    levels_afc   = np.linspace(-lim_afc,   lim_afc,   21)

    # T-adv − EPALL contour levels: step-based, capped at data range
    _max_tadv = _sym_lim('adv_T_850_mep')
    _cap  = min(TADV_EPALL_CAP, _max_tadv)
    tadv_pos = np.arange(TADV_EPALL_STEP, _cap + TADV_EPALL_STEP * 0.5, TADV_EPALL_STEP)
    tadv_neg = -tadv_pos[::-1]

    # KE-adv − EPALL contour levels
    _max_keadv = _sym_lim('ke_adv_250_mep')
    _keadv_cap = min(KEADV_EPALL_CAP, _max_keadv)
    keadv_pos = np.arange(KEADV_EPALL_STEP, _keadv_cap + KEADV_EPALL_STEP * 0.5, KEADV_EPALL_STEP)
    keadv_neg = -keadv_pos[::-1]

    # ── GridSpec: 3 rows × 4 cols (EP1 | EP2 | EP3 | colorbar) ──────────────
    fig = plt.figure(figsize=FIGSIZE)
    gs = gridspec.GridSpec(
        3, 4,
        width_ratios=[1, 1, 1, 0.055],
        hspace=0.07,
        wspace=0.07,
        left=0.05, right=0.94, top=0.95, bottom=0.04,
    )

    # =========================================================================
    # ROW 0 — Upper-level / baroclinic structure departure
    # (PV@200) − EPALL  shading
    # (EGR) − EPALL     contours  (steelblue dashed / firebrick solid)
    # SLP total (EP composite)  thin contours
    # =========================================================================
    print("  Row 1: (PV@200)−EPALL + EGR−EPALL ctr + Δwind250 + SLP ...", flush=True)
    im_r0 = None
    for col, ep in enumerate(eps):
        d  = ep_data[ep]
        ax = fig.add_subplot(gs[0, col])

        im = ax.contourf(d['x_2d'], d['y_2d'], d['pv_200_mep'],
                         levels=levels_pv200, cmap=CMAP_PV200_ANOM, extend='both')
        if col == 0:
            im_r0 = im

        # EGR − EPALL contours
        egr_mep = d['egr_mep']
        pos_egr = EGR_EPALL_POS_LEVELS[
            (EGR_EPALL_POS_LEVELS >= np.nanmin(egr_mep)) &
            (EGR_EPALL_POS_LEVELS <= np.nanmax(egr_mep))
        ]
        neg_egr = EGR_EPALL_NEG_LEVELS[
            (EGR_EPALL_NEG_LEVELS >= np.nanmin(egr_mep)) &
            (EGR_EPALL_NEG_LEVELS <= np.nanmax(egr_mep))
        ]
        if len(pos_egr):
            cs = ax.contour(d['x_2d'], d['y_2d'], egr_mep,
                            levels=pos_egr,
                            colors='firebrick', linewidths=2.0, linestyles='solid',
                            alpha=0.90, zorder=5)
            ax.clabel(cs, inline=True, fontsize=7, fmt='%.2f')
        if len(neg_egr):
            cs = ax.contour(d['x_2d'], d['y_2d'], egr_mep,
                            levels=neg_egr,
                            colors='steelblue', linewidths=2.0, linestyles='dashed',
                            alpha=0.90, zorder=5)
            ax.clabel(cs, inline=True, fontsize=7, fmt='%.2f')

        _add_slp_contours(ax, d['x_2d'], d['y_2d'], d['msl_hpa'])
        _add_lec_box(ax)
        _mark_center(ax)
        _ax_setup(ax, d['x'], d['y'], show_ylabels=(col == 0))
        _panel_label(ax, PANEL_LABELS[0][col])
        ax.set_title(f"{ep} − EPALL  (n={d['n_cases']})",
                     fontsize=PANEL_TITLESIZE, fontweight='bold', pad=4)

    _add_colorbar(fig, gs[0, 3], im_r0, r"(PV$_{200}$ − EPALL) (PVU)")

    # =========================================================================
    # ROW 1 — Low-level frontal / thermal structure departure
    # (PV@850) − EPALL  shading
    # (T-adv) − EPALL   contours  (steelblue dashed / firebrick solid)
    # (u,v)_850 − EPALL wind vectors
    # (Z@850) − EPALL   thin contours
    # =========================================================================
    print("  Row 2: (PV@850)−EPALL + T-adv−EPALL ctr + Δwind850 + SLP ...", flush=True)
    im_r1 = None
    for col, ep in enumerate(eps):
        d  = ep_data[ep]
        ax = fig.add_subplot(gs[1, col])

        im = ax.contourf(d['x_2d'], d['y_2d'], d['pv_850_mep'],
                         levels=levels_pv850, cmap=CMAP_PV850_ANOM, extend='both')
        if col == 0:
            im_r1 = im

        tadv = d['adv_T_850_mep']
        neg_v = tadv_neg[tadv_neg >= np.nanmin(tadv)]
        if len(neg_v):
            ax.contour(d['x_2d'], d['y_2d'], tadv,
                       levels=neg_v,
                       colors='steelblue', linewidths=2.0,
                       linestyles='dashed', alpha=0.9, zorder=5)
        pos_v = tadv_pos[tadv_pos <= np.nanmax(tadv)]
        if len(pos_v):
            ax.contour(d['x_2d'], d['y_2d'], tadv,
                       levels=pos_v,
                       colors='firebrick', linewidths=2.0,
                       linestyles='solid', alpha=0.9, zorder=5)

        _add_wind_vectors(ax, d['x_2d'], d['y_2d'], d['u_850_mep'], d['v_850_mep'],
                          scale=VECTOR_SCALE_850, key_u=QUIVER_KEY_U_850,
                          add_key=(col == 2))
        _add_lec_box(ax)
        _mark_center(ax)
        _ax_setup(ax, d['x'], d['y'], show_ylabels=(col == 0))
        _panel_label(ax, PANEL_LABELS[1][col])

    _add_colorbar(fig, gs[1, 3], im_r1, r"(PV$_{850}$ − EPALL) (PVU)")

    # =========================================================================
    # ROW 2 — Jet-level energetics departure + barotropic favorability
    # AFC − EPALL         shading
    # (KE-adv) − EPALL   contours  (steelblue dashed / firebrick solid)
    # (u,v)_250 − EPALL   wind vectors
    # RK sign-reversal    hatching (TOTAL EP composite)
    # (Z@250) − EPALL    thin contours
    # =========================================================================
    print("  Row 3: AFC−EPALL + Δwind250 + RK (total) hatching + SLP ...", flush=True)
    im_r2 = None
    for col, ep in enumerate(eps):
        d  = ep_data[ep]
        ax = fig.add_subplot(gs[2, col])

        im = ax.contourf(d['x_2d'], d['y_2d'], d['afc_250_mep'],
                         levels=levels_afc, cmap=CMAP_AFC, extend='both')
        if col == 0:
            im_r2 = im

        # RK hatching: use TOTAL EP composite
        rk_mask = meridional_sign_reversal_mask(d['rk_criterion'],
                                                half_window=RK_HATCH_HALF_WINDOW)
        with mpl.rc_context({'hatch.color': HATCH_COLOR,
                              'hatch.linewidth': HATCH_LW}):
            ax.contourf(d['x_2d'], d['y_2d'], rk_mask.astype(float),
                        levels=[0.5, 1.5],
                        colors=['none'],
                        hatches=[HATCH_PATTERN],
                        zorder=6)

        # KE-adv − EPALL contours: steelblue dashed / firebrick solid
        ke = d['ke_adv_250_mep']
        neg_ke = keadv_neg[keadv_neg >= np.nanmin(ke)]
        pos_ke = keadv_pos[keadv_pos <= np.nanmax(ke)]
        if len(neg_ke):
            ax.contour(d['x_2d'], d['y_2d'], ke, levels=neg_ke,
                       colors='steelblue', linewidths=2.0,
                       linestyles='dashed', alpha=0.9, zorder=5)
        if len(pos_ke):
            ax.contour(d['x_2d'], d['y_2d'], ke, levels=pos_ke,
                       colors='firebrick', linewidths=2.0,
                       linestyles='solid', alpha=0.9, zorder=5)

        _add_wind_vectors(ax, d['x_2d'], d['y_2d'], d['u_250_mep'], d['v_250_mep'],
                          scale=VECTOR_SCALE_250, key_u=QUIVER_KEY_U_250,
                          add_key=(col == 2))
        _add_lec_box(ax)
        _mark_center(ax)
        _ax_setup(ax, d['x'], d['y'],
                  show_xlabels=True, show_ylabels=(col == 0))
        _panel_label(ax, PANEL_LABELS[2][col])

    _add_colorbar(fig, gs[2, 3], im_r2, r"(AFC$_{250}$ − EPALL) (W m$^{-2}$)")

    # ── Save   ────────────────────────────────────────────────────────
    plt.savefig(output_png, dpi=DPI, bbox_inches='tight')
    print(f"  Saved: {output_png}", flush=True)
    plt.close()


# ============================================================================
# MAIN
# ============================================================================

def main():
    """Generate Figure 7: EP − EPALL dynamical composites (3×3)."""
    print("=" * 80)
    print("FIGURE 7 — EP − EPALL DYNAMICAL COMPOSITES (3×3)")
    print("Anomaly = EP_composite − EPALL_composite")
    print("=" * 80)

    # ── Load raw composites ───────────────────────────────────────────────────
    print("\nLoading composite files ...\n")
    raw = load_raw_composites()

    # ── Compute EPALL-relative differences ───────────────────────────────────
    print("\nComputing EPALL-relative differences ...")
    ep_data = {}
    for ep in ['EP1', 'EP2', 'EP3']:
        ep_data[ep] = compute_epall_relative(raw, ep)
        d = ep_data[ep]
        print(f"\n  {ep} (n={d['n_cases']}):")
        print(f"    (PV@200)−EPALL  [{d['pv_200_mep'].min():.3f}, {d['pv_200_mep'].max():.3f}] PVU")
        print(f"    (PV@850)−EPALL  [{d['pv_850_mep'].min():.4f}, {d['pv_850_mep'].max():.4f}] PVU")
        print(f"    (EGR)−EPALL     [{d['egr_mep'].min():.3f}, {d['egr_mep'].max():.3f}] day⁻¹")
        print(f"    (T-adv)−EPALL   [{d['adv_T_850_mep'].min():.4f}, {d['adv_T_850_mep'].max():.4f}] K h⁻¹")
        print(f"    (AFC)−EPALL     [{d['afc_250_mep'].min():.5f}, {d['afc_250_mep'].max():.5f}] W m⁻²")
        rk_mask = meridional_sign_reversal_mask(d['rk_criterion'],
                                                half_window=RK_HATCH_HALF_WINDOW)
        coverage = rk_mask.sum() / rk_mask.size * 100
        print(f"    RK coverage (total composite): {coverage:.1f}% of domain")

    for ds in raw.values():
        ds.close()

    print(f"\n{'='*80}")
    print("Creating figure ...")
    print(f"{'='*80}\n")

    create_figure(ep_data, OUTPUT_PNG)

    print(f"\n{'='*80}")
    print("Figure 7 complete!")
    print(f"  PNG : {OUTPUT_PNG}")
    print(f"{'='*80}\n")
    return 0


if __name__ == '__main__':
    sys.exit(main())
