#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Figure 7: EP1 Instability Analysis - Multi-Scale Composite

Publication-ready 4×3 composite figure showing baroclinic and barotropic
instability metrics for EP1 cyclones across three spatial scales:
local (5°), mesoscale (15°), and synoptic (30°).

Data source:
  • Precomputed composites: data/era5_ep1/precomputed_composites_{domain}.nc
  • Generated by scripts/ep1_ibc_ibt_analysis/step3_precompute_composites.py

Rows (diagnostics):
  1. Rayleigh-Kuo (RK) criterion 2D map  (∂η/∂y at Ck ≈ 350 hPa)
  2. RK criterion zonal-mean profile
  3. Baroclinic PV at Ca level (975 hPa, shaded)
       + PV at 200 hPa (green contours, 2 PVU tropopause dashed)
  4. Eady Growth Rate (EGR, shaded)
       + SLP (black contours)

Columns: local (5°) | mesoscale (15°) | synoptic (30°)
12 panels total, labeled (a)–(l)

Outputs:
  • figures/main/7_ep1_instability_composite_4x3.png (300 DPI)

Author: Danilo Couto de Souza
Date: February 2026
"""

import sys
from pathlib import Path

# Add project root to path
BASE_DIR = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(BASE_DIR / 'scripts'))

import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
from matplotlib import gridspec
from matplotlib.lines import Line2D
import warnings

warnings.filterwarnings('ignore')

# Configuration
DATA_DIR = BASE_DIR / "data" / "era5_ep1"
RESULTS_DIR = BASE_DIR / "results" / "ep1_vertical"
FIGURES_DIR = BASE_DIR / "figures" / "main"
FIGURES_DIR.mkdir(parents=True, exist_ok=True)

DPI = 300
DOMAINS = ['local', 'mesoscale', 'synoptic']
DOMAIN_LABELS = ['5°', '15°', '30°']
COMPOSITE_FILES = {
    d: DATA_DIR / f'precomputed_composites_{d}.nc' for d in DOMAINS
}

# --------------------------------------------------------------------------
# Font size configuration (centralized)
# --------------------------------------------------------------------------
BASE_FONTSIZE = 11
AXIS_LABELSIZE = 12
PANEL_TITLESIZE = 13
TICK_LABELSIZE = 12
LEGEND_FONTSIZE = 12
CBAR_LABELSIZE = 12
ANNOTATION_FONTSIZE = 12
FIGURE_TITLESIZE = 14

# Apply font sizes to rcParams for consistency
plt.rcParams.update({
    'font.size': BASE_FONTSIZE,
    'axes.labelsize': AXIS_LABELSIZE,
    'axes.titlesize': PANEL_TITLESIZE,
    'xtick.labelsize': TICK_LABELSIZE,
    'ytick.labelsize': TICK_LABELSIZE,
    'legend.fontsize': LEGEND_FONTSIZE,
    'figure.titlesize': FIGURE_TITLESIZE,
    'font.family': 'sans-serif',
    'figure.dpi': 100,
    'savefig.dpi': DPI,
    'savefig.bbox': 'tight',
    'axes.grid': False,
})


# ============================================================================
# Load precomputed composites
# ============================================================================

def load_precomputed_composites(domain):
    """
    Load precomputed composite fields for a given domain from NetCDF.

    Variables read (all prefixed with domain name):
      deta_dy, deta_dy_zonal, pv_ca, pv_200, egr, msl

    Returns
    -------
    dict with keys:
      deta_dy_mean, deta_dy_zonal_mean, pv_mean, pv_200_mean,
      egr_day_mean, msl_mean, x, y, x_2d, y_2d, n_cases
    """
    nc_file = COMPOSITE_FILES[domain]
    if not nc_file.exists():
        raise FileNotFoundError(
            f"Composite file not found: {nc_file}\n"
            f"Run scripts/ep1_ibc_ibt_analysis/step3_precompute_composites.py first."
        )

    print(f"  Loading {nc_file.name} ...", flush=True)
    ds = xr.open_dataset(nc_file)

    p = f"{domain}_"  # variable name prefix

    # ---- required fields ----
    deta_dy  = ds[f"{p}deta_dy"].values        # (y, x)
    egr      = ds[f"{p}egr"].values            # (y, x)
    pv_ca    = ds[f"{p}pv_ca"].values          # (y, x)  — at Ca level (975 hPa)

    # deta_dy_zonal may be 1-D (y,) or 2-D (y, x); keep as 1-D mean
    dz_raw = ds[f"{p}deta_dy_zonal"].values
    deta_dy_zonal = dz_raw if dz_raw.ndim == 1 else dz_raw.mean(axis=-1)

    # ---- optional fields (may be absent / all-NaN) ----
    def _load_opt(name):
        key = f"{p}{name}"
        if key in ds:
            arr = ds[key].values
            return None if np.all(np.isnan(arr)) else arr
        return None

    pv_200 = _load_opt("pv_200")   # (y, x) in PVU, or None
    msl    = _load_opt("msl")      # (y, x) in Pa, or None

    # ---- use coordinates stored in the file (y is N→S: positive→negative) ----
    y_coord = f'y_{domain}'
    x_coord = f'x_{domain}'

    with xr.open_dataset(nc_file) as _ds:
        y = _ds[y_coord].values   # e.g. [+2.5 … –2.5]  (N→S)
        x = _ds[x_coord].values   # e.g. [–2.5 … +2.5]  (W→E)

    x_2d, y_2d = np.meshgrid(x, y)

    return {
        'deta_dy_mean':       deta_dy,
        'deta_dy_zonal_mean': deta_dy_zonal,
        'pv_mean':            pv_ca,
        'pv_200_mean':        pv_200,
        'egr_day_mean':       egr,
        'msl_mean':           msl,
        'x':    x,
        'y':    y,
        'x_2d': x_2d,
        'y_2d': y_2d,
    }


# ============================================================================
# Figure creation
# ============================================================================

def _ax_setup(ax, data):
    """Common axis setup: limits, aspect, grid, hide tick labels."""
    ax.set_xlim(data['x'].min(), data['x'].max())
    ax.set_ylim(data['y'].min(), data['y'].max())
    try:
        ax.set_box_aspect(1)
    except Exception:
        ax.set_aspect('equal')
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.set_xticklabels([])
    ax.set_yticklabels([])


def create_main_figure(data_dict, n_cases, output_file):
    """
    Create main 4×3 composite figure.

    Rows:
      0 – RK criterion 2D map (∂η/∂y)
      1 – RK zonal-mean profile
      2 – Baroclinic PV at Ca (975 hPa, shaded) + PV@200 hPa (green contours)
      3 – EGR (shaded) + SLP (black contours)

    Columns: local (5°) | mesoscale (15°) | synoptic (30°)
    """
    fig = plt.figure(figsize=(8, 10))
    gs = gridspec.GridSpec(4, 4, hspace=0.12, wspace=0.06,
                           left=0.05, right=0.98, top=0.98, bottom=0.03,
                           width_ratios=[1, 1, 1, 0.12])

    panel_labels = [
        ['(a)', '(b)', '(c)'],
        ['(d)', '(e)', '(f)'],
        ['(g)', '(h)', '(i)'],
        ['(j)', '(k)', '(l)'],
    ]

    # -------------------------------------------------------------------------
    # Row 0 – RK 2D (∂η/∂y)
    # -------------------------------------------------------------------------
    print("  Creating Row 1: RK 2D (∂η/∂y)...")
    rk_max_abs = max(np.nanmax(np.abs(data_dict[d]['deta_dy_mean'])) for d in DOMAINS)
    levels_rk = np.linspace(-rk_max_abs, rk_max_abs, 21)

    for col, domain in enumerate(DOMAINS):
        ax = fig.add_subplot(gs[0, col])
        data = data_dict[domain]

        im = ax.contourf(data['x_2d'], data['y_2d'], data['deta_dy_mean'],
                         levels=levels_rk, cmap='RdBu_r', extend='both')
        ax.contour(data['x_2d'], data['y_2d'], data['deta_dy_mean'],
                   levels=[0], colors='k', linewidths=1.5)
        ax.plot(0, 0, 'k*', markersize=15, markeredgecolor='white', markeredgewidth=1.5)
        _ax_setup(ax, data)
        ax.text(0.01, 0.98, panel_labels[0][col], transform=ax.transAxes,
                fontsize=ANNOTATION_FONTSIZE + 1, fontweight='bold', ha='left', va='top')

        if col == 2:
            cax = fig.add_subplot(gs[0, 3])
            cb = plt.colorbar(im, cax=cax)
            cb.set_label(r'∂η/∂y (s$^{-1}$ m$^{-1}$)', fontsize=CBAR_LABELSIZE)
            cb.ax.tick_params(labelsize=CBAR_LABELSIZE)
            cb.ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x:.2e}'))
            cax.yaxis.set_ticks_position('right')
            cax.xaxis.set_visible(False)

    # -------------------------------------------------------------------------
    # Row 1 – RK zonal-mean profile
    # -------------------------------------------------------------------------
    print("  Creating Row 2: RK zonal-mean...")
    for col, domain in enumerate(DOMAINS):
        ax = fig.add_subplot(gs[1, col])
        data = data_dict[domain]

        ax.axvline(0, color='k', linestyle='--', linewidth=1, alpha=0.5)
        ax.axhline(0, color='k', linestyle='-', linewidth=1, alpha=0.3)
        ax.plot(data['deta_dy_zonal_mean'], data['y'], color='b', linewidth=2.5)
        ax.set_ylim(data['y'].min(), data['y'].max())
        ax.grid(True, alpha=0.3)
        try:
            ax.set_box_aspect(1)
        except Exception:
            pass
        ax.set_xticklabels([])
        ax.set_yticklabels([])
        ax.text(0.01, 0.98, panel_labels[1][col], transform=ax.transAxes,
                fontsize=ANNOTATION_FONTSIZE + 1, fontweight='bold', ha='left', va='top')

        if col == 2:
            # Place a minimal legend in the cbar slot
            legend_ax = fig.add_subplot(gs[1, 3])
            legend_ax.axis('off')
            handles = [Line2D([0], [0], color='b', linewidth=2.5)]
            legend_ax.legend(handles, ['Composite\nmean'], loc='center',
                             frameon=True, fontsize=LEGEND_FONTSIZE, handlelength=2)

    # -------------------------------------------------------------------------
    # Row 2 – Baroclinic PV@975 hPa (shaded) + PV@200 hPa (green contours)
    # -------------------------------------------------------------------------
    print("  Creating Row 3: PV@975 + PV@200 contours...")
    pv_min = min(np.nanmin(data_dict[d]['pv_mean'] * 1e6) for d in DOMAINS)
    pv_levels = np.linspace(pv_min, 0, 21)

    for col, domain in enumerate(DOMAINS):
        ax = fig.add_subplot(gs[2, col])
        data = data_dict[domain]

        im = ax.contourf(data['x_2d'], data['y_2d'], data['pv_mean'] * 1e6,
                         levels=pv_levels, cmap='RdYlBu_r', extend='both')

        # PV@200 hPa — green contours (values already in PVU from step3)
        pv200 = data.get('pv_200_mean')
        if pv200 is not None:
            # Negative PVU contours (Southern Hemisphere: PV < 0)
            pv200_pvu = pv200 * 1e6 if np.nanmax(np.abs(pv200)) < 1e-3 else pv200
            pv200_lvls = np.linspace(np.nanmin(pv200_pvu), np.nanmax(pv200_pvu), 8)
            pv200_lvls = [v for v in pv200_lvls if v != 0]
            if pv200_lvls:
                cs200 = ax.contour(data['x_2d'], data['y_2d'], pv200_pvu,
                                   levels=pv200_lvls, colors='green',
                                   linewidths=0.9, alpha=0.8)
            # 2-PVU tropopause marker (use ±2 depending on hemisphere sign)
            trop_val = -2.0 if np.nanmean(pv200_pvu) < 0 else 2.0
            ax.contour(data['x_2d'], data['y_2d'], pv200_pvu,
                       levels=[trop_val], colors='darkgreen',
                       linewidths=2.0, linestyles='--')
        else:
            print(f"    ⚠ No PV@200 for {domain}")

        ax.plot(0, 0, 'k*', markersize=15, markeredgecolor='white', markeredgewidth=1.5)
        _ax_setup(ax, data)
        ax.text(0.01, 0.98, panel_labels[2][col], transform=ax.transAxes,
                fontsize=ANNOTATION_FONTSIZE + 1, fontweight='bold', ha='left', va='top')

        if col == 2:
            cax = fig.add_subplot(gs[2, 3])
            cb = plt.colorbar(im, cax=cax)
            cb.set_label(r'PV$_{975}$ (PVU)', fontsize=CBAR_LABELSIZE)
            cb.ax.tick_params(labelsize=CBAR_LABELSIZE)
            cb.ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x:.2f}'))
            cax.yaxis.set_ticks_position('right')
            cax.xaxis.set_visible(False)

    # -------------------------------------------------------------------------
    # Row 3 – EGR (shaded) + SLP (black contours)
    # -------------------------------------------------------------------------
    print("  Creating Row 4: EGR + SLP contours...")
    egr_min_g = max(0, min(np.nanpercentile(data_dict[d]['egr_day_mean'], 1) for d in DOMAINS))
    egr_max_g = max(np.nanpercentile(data_dict[d]['egr_day_mean'], 99) for d in DOMAINS)
    egr_levels = (np.linspace(egr_min_g, egr_max_g, 21)
                  if egr_max_g > egr_min_g else np.linspace(0, 4, 21))

    for col, domain in enumerate(DOMAINS):
        ax = fig.add_subplot(gs[3, col])
        data = data_dict[domain]

        im = ax.contourf(data['x_2d'], data['y_2d'], data['egr_day_mean'],
                         levels=egr_levels, cmap='YlOrRd', extend='both')

        # SLP — black contours (values in Pa → convert to hPa)
        msl = data.get('msl_mean')
        if msl is not None:
            msl_hpa = msl / 100.0 if np.nanmean(msl) > 2000 else msl
            slp_range = np.nanmax(msl_hpa) - np.nanmin(msl_hpa)
            if slp_range > 0.5:
                slp_levels = np.arange(
                    np.floor(np.nanmin(msl_hpa) / 2) * 2,
                    np.ceil(np.nanmax(msl_hpa) / 2) * 2 + 2, 2
                )
                cs_slp = ax.contour(data['x_2d'], data['y_2d'], msl_hpa,
                                    levels=slp_levels, colors='black',
                                    linewidths=0.9, alpha=0.85)
                ax.clabel(cs_slp, fmt='%g', fontsize=8, inline=True)
        else:
            print(f"    ⚠ No SLP for {domain}")

        ax.plot(0, 0, 'k*', markersize=15, markeredgecolor='white', markeredgewidth=1.5)
        _ax_setup(ax, data)
        ax.text(0.01, 0.98, panel_labels[3][col], transform=ax.transAxes,
                fontsize=ANNOTATION_FONTSIZE + 1, fontweight='bold', ha='left', va='top')

        mean_egr = np.nanmean(data['egr_day_mean'])
        ax.text(0.98, 0.02, f'Mean: {mean_egr:.2f} day$^{{-1}}$',
                transform=ax.transAxes, fontsize=ANNOTATION_FONTSIZE,
                ha='right', va='bottom',
                bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

        if col == 2:
            cax = fig.add_subplot(gs[3, 3])
            cb = plt.colorbar(im, cax=cax)
            cb.set_label(r'EGR (day$^{-1}$)', fontsize=CBAR_LABELSIZE)
            cb.ax.tick_params(labelsize=CBAR_LABELSIZE)
            cb.ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x:.2f}'))
            cax.yaxis.set_ticks_position('right')
            cax.xaxis.set_visible(False)

    # Column headers
    for col, label in enumerate(DOMAIN_LABELS):
        fig.axes[col * 1].set_title(label, fontsize=PANEL_TITLESIZE, fontweight='bold',
                                    pad=3)

    plt.savefig(output_file, dpi=DPI, bbox_inches='tight')
    plt.close()
    print(f"  ✓ Saved: {output_file.name}")


# ============================================================================
# Main execution
# ============================================================================

def main():
    """Generate Figure 7: EP1 instability composite (4×3)."""

    print("=" * 80)
    print("EP1 INSTABILITY COMPOSITE FIGURE (4×3)")
    print("=" * 80)

    # Check composite files
    missing = [d for d in DOMAINS if not COMPOSITE_FILES[d].exists()]
    if missing:
        print(f"\n❌ Missing composite files for: {missing}")
        print("   Run scripts/ep1_ibc_ibt_analysis/step3_precompute_composites.py first.")
        return

    # Load precomputed composites (one file per domain)
    data_dict = {}
    n_cases = None
    for domain in DOMAINS:
        print(f"\n{'='*60}")
        print(f"Loading {domain.upper()} composite")
        print(f"{'='*60}")
        data_dict[domain] = load_precomputed_composites(domain)

        # Report optional field availability
        has_pv200 = data_dict[domain]['pv_200_mean'] is not None
        has_msl   = data_dict[domain]['msl_mean']    is not None
        print(f"  PV@200={'✓' if has_pv200 else '✗ (not available)'}  "
              f"SLP={'✓' if has_msl else '✗ (not available)'}")

    print(f"\n{'='*80}")
    print("Creating figure...")
    print(f"{'='*80}")

    output_file = FIGURES_DIR / "7_ep1_instability_composite_4x3.png"
    create_main_figure(data_dict, n_cases, output_file)

    print(f"\n{'='*80}")
    print("✅ Figure 7 created successfully!")
    print(f"{'='*80}")
    print(f"\nOutput: {output_file}")
    print()


if __name__ == "__main__":
    main()
