#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Figure 8: EP1 vs EP2 Dynamical Composites — 3×2 Layout

Publication-ready figure comparing the composite dynamical structure of
Energy Pattern 1 (EP1) and Energy Pattern 2 (EP2) cyclones during their
intensification phase. The 3×2 layout organises diagnostics by physical
mechanism, allowing direct visual comparison between patterns.

Layout:
  Columns : EP1 (n=444)  |  EP2 (n=979)
  ─────────────────────────────────────────────────────────────────────
  Row 1   Upper-level forcing / baroclinic environment
            Shading  : PV anomaly at 200 hPa  (pv_200_anom)          [PVU]
            Contours : Eady Growth Rate ≥ 0.5 (egr)                   [day⁻¹]
            Vectors  : Wind anomaly at 250 hPa (u_250_prime, v_250_prime) [m s⁻¹]
            Thin ctr : SLP anomaly             (msl_anom)             [hPa]
  ─────────────────────────────────────────────────────────────────────
  Row 2   Low-level frontal / diabatic response
            Shading  : PV anomaly at 850 hPa  (pv_850_anom)   [PVU]
            Contours : T-advection total      (adv_T_850)      [K h⁻¹]
                       negative = dashed blue (cold), positive = solid red (warm)
            Vectors  : Total wind at 850 hPa  (u_850, v_850)   [m s⁻¹]
            Thin ctr : SLP                    (msl)            [hPa]
  ─────────────────────────────────────────────────────────────────────
  Row 3   Jet-level energetics / barotropic favorability
            Shading  : Ageostrophic Flux Convergence (afc_250) [W m⁻²]
            Vectors  : Total wind at 250 hPa  (u_250, v_250)   [m s⁻¹]
            Hatching : RK meridional sign-reversal mask (see below)

Hatching definition — RK meridional sign-reversal mask:
  For each grid point (i, j), the mask is True when the field
  rk_criterion_250 contains both strictly positive and strictly negative
  values within a ±RK_HATCH_HALF_WINDOW-point meridional neighborhood:

      mask[i,j] = True  iff
          min(rk[i-w : i+w+1, j]) < 0  AND  max(rk[i-w : i+w+1, j]) > 0
      where w = RK_HATCH_HALF_WINDOW (default 1 → 3-point / 0.5° window)

  Physical meaning: identifies the zero-crossing band of ∂η/∂y along the
  meridional direction. A meridional sign reversal of ∂η/∂y is a necessary
  (but not sufficient) condition for barotropic instability by the
  Rayleigh-Kuo theorem (Rayleigh 1880; Kuo 1949). The hatching therefore
  highlights where this necessary condition is locally met — it does NOT
  simply mark where rk < 0 pointwise.

Why SLP appears in all rows:
  SLP contours (thin, semi-transparent) provide a common spatial reference
  — the cyclone depression and associated pressure gradient — allowing the
  reader to directly relate each dynamic field to the surface cyclone
  location. They are intentionally subdued so as not to compete with the
  primary diagnostic shading.

Why total wind (not anomaly) in Rows 1–3:
  Total winds show the full dynamical context — the jet-stream position and
  the low-level circulation pattern — relevant for interpreting each
  diagnostic field. Total winds at 250 hPa directly characterise the
  upper-level jet environment and the eddy kinetic energy environment,
  while total winds at 850 hPa reveal the low-level wind structure
  associated with frontal zones and temperature advection.

Data source:
  data/era5_ep_structure/precomputed_composites_ep1.nc  (EP1: 444 cases)
  data/era5_ep_structure/precomputed_composites_ep2.nc  (EP2: 979 cases)
  Generated by: scripts/ep_structure_analysis/step3_precompute_composites.py

Outputs:
  figures/main/8_ep1_ep2_dynamical_composites.png  (300 DPI)

Author: Danilo Couto de Souza
Date: March 2026
"""

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(BASE_DIR / 'scripts'))

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import xarray as xr
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import gridspec
from matplotlib.patches import Rectangle

# ============================================================================
# CONFIGURABLE PARAMETERS  (change here — not buried in plotting code)
# ============================================================================

DPI = 300
FIGSIZE = (9, 12)

# ── Input data ───────────────────────────────────────────────────────────────
DATA_DIR = BASE_DIR / 'data' / 'era5_ep_structure'
COMPOSITE_FILES = {
    'EP1': DATA_DIR / 'precomputed_composites_ep1.nc',
    'EP2': DATA_DIR / 'precomputed_composites_ep2.nc',
}

# ── Output ───────────────────────────────────────────────────────────────────
FIGURES_DIR = BASE_DIR / 'figures' / 'main'
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PNG = FIGURES_DIR / '8_ep1_ep2_dynamical_composites.png'

# ── Unit conversions ─────────────────────────────────────────────────────────
PV_SCALE    = 1e6      # K m² kg⁻¹ s⁻¹ (SI)  →  PVU
ADV_T_SCALE = 3600.0   # K s⁻¹               →  K h⁻¹
SLP_SCALE   = 1e-2     # Pa                  →  hPa

# ── Row 1: EGR contour levels [day⁻¹] — only ≥ 0.5 day⁻¹ ───────────────────
# Threshold of 0.5 day⁻¹ focuses on the enhanced-instability core.
# Data range across both EPs is approximately 0.29–0.69 day⁻¹.
EGR_CONTOUR_LEVELS = np.array([0.50, 0.55, 0.60])

# ── Row 2: Total temperature advection contour levels [K h⁻¹] ───────────────
# Total adv_T_850 range (K h⁻¹): ~−0.144 to +0.140.
# Negative (cold advection): dashed blue.  Positive (warm advection): solid red.
TADV_NEG_LEVELS = np.array([-0.120, -0.080, -0.040])  # K h⁻¹
TADV_POS_LEVELS = np.array([0.040,  0.080,  0.120])    # K h⁻¹

# ── SLP contour interval [hPa] ───────────────────────────────────────────────
SLP_INTERVAL = 2.0      # 2-hPa spacing covers the ~20 hPa composite range cleanly

# ── Wind vectors ─────────────────────────────────────────────────────────────
# skip=16 → one vector every 4° on a 0.25°-grid 30°-domain ≈ 7 vectors/side
VECTOR_SKIP      = 16
# Scale for 250 hPa total winds (u_250 range ≈ 15–37 m/s):
# scale=500 → 20 m/s arrow ≈ 20/500 = 4% of domain extent
VECTOR_SCALE_250 = 500
QUIVER_KEY_U_250 = 20.0   # reference vector for quiver key [m s⁻¹]
# Scale for 850 hPa total winds (u_850 range ≈ 1–12 m/s):
VECTOR_SCALE_850 = 200
QUIVER_KEY_U_850 = 5.0    # reference vector for quiver key [m s⁻¹]

# ── RK meridional sign-reversal hatching ─────────────────────────────────────
# half_window=1 → 3-point (0.5°) meridional neighbourhood
RK_HATCH_HALF_WINDOW = 1
HATCH_PATTERN = '///'   # forward-slash hatching, medium density
HATCH_COLOR   = 'dimgray'
HATCH_LW      = 0.7     # linewidth inside the hatch fill

# ── Colormaps ────────────────────────────────────────────────────────────────
# RdBu_r: blue=negative, red=positive (physical colour convention)
CMAP_PV200_ANOM = 'RdBu_r'   # PV@200 anom: blue=trough deepening, red=ridge
CMAP_PV850_ANOM = 'RdBu_r'   # PV@850 anom: blue=cyclonic, red=anticyclonic
CMAP_AFC        = 'RdBu_r'   # AFC: red=energy source for eddies, blue=sink

# ── Font sizes (consistent with Figure 7 and project convention) ─────────────
BASE_FONTSIZE       = 11
PANEL_TITLESIZE     = 12
TICK_LABELSIZE      = 9
CBAR_LABELSIZE      = 9
ANNOTATION_FONTSIZE = 12

# Apply globally
plt.rcParams.update({
    'font.size':         BASE_FONTSIZE,
    'axes.labelsize':    BASE_FONTSIZE,
    'axes.titlesize':    PANEL_TITLESIZE,
    'xtick.labelsize':   TICK_LABELSIZE,
    'ytick.labelsize':   TICK_LABELSIZE,
    'legend.fontsize':   TICK_LABELSIZE,
    'figure.dpi':        100,
    'savefig.dpi':       DPI,
    'savefig.bbox':      'tight',
    'axes.grid':         False,
    'font.family':       'sans-serif',
})


# ============================================================================
# DATA LOADING
# ============================================================================

def load_ep_composite(ep_label):
    """
    Load precomputed composite fields from NetCDF for EP1 or EP2.

    All required variables are converted to display units here; the
    plotting code only receives values in the units listed below.

    Parameters
    ----------
    ep_label : str   'EP1' or 'EP2'

    Returns
    -------
    dict with keys:
      pv_200_anom  : 2-D (ny, nx), PVU
      pv_850_anom  : 2-D (ny, nx), PVU
      egr          : 2-D (ny, nx), day⁻¹
      adv_T_850    : 2-D (ny, nx), K h⁻¹  (total, not anomaly)
      msl_hpa      : 2-D (ny, nx), hPa
      afc_250      : 2-D (ny, nx), W m⁻²
      u_250, v_250 : 2-D (ny, nx), m s⁻¹  (total wind at 250 hPa)
      u_850, v_850 : 2-D (ny, nx), m s⁻¹  (total wind at 850 hPa)
      rk_criterion : 2-D (ny, nx), m⁻¹ s⁻¹ (kept in SI for sign-reversal mask)
      x, y         : 1-D coordinate arrays, degrees (storm-relative)
      x_2d, y_2d   : 2-D mesh grids
      n_cases      : int
    """
    nc_file = COMPOSITE_FILES[ep_label]
    if not nc_file.exists():
        raise FileNotFoundError(
            f"Composite file not found: {nc_file}\n"
            "Run scripts/ep_structure_analysis/step3_precompute_composites.py first."
        )

    print(f"  Loading {nc_file.name} ...", flush=True)
    ds = xr.open_dataset(nc_file)
    n_cases = int(ds.attrs.get('n_cases', 0))

    def _require(var):
        if var not in ds:
            raise KeyError(
                f"Required variable '{var}' not found in {nc_file.name}.\n"
                f"Available variables: {sorted(ds.data_vars)}"
            )
        return ds[var].values.copy()

    x   = ds['x'].values   # relative longitude [°], shape (121,)
    y   = ds['y'].values   # relative latitude  [°], shape (121,)
    x_2d, y_2d = np.meshgrid(x, y)

    data = {
        # PV anomalies: SI (K m² kg⁻¹ s⁻¹) → PVU
        'pv_200_anom' : _require('pv_200_anom')  * PV_SCALE,
        'pv_850_anom' : _require('pv_850_anom')  * PV_SCALE,
        # EGR: already in day⁻¹
        'egr'         : _require('egr'),
        # Temperature advection TOTAL: K s⁻¹ → K h⁻¹
        'adv_T_850'   : _require('adv_T_850')    * ADV_T_SCALE,
        # SLP total: Pa → hPa (used in rows c/d and e/f)
        'msl_hpa'     : _require('msl')          * SLP_SCALE,
        # SLP anomaly: Pa → hPa (used in rows a/b)
        'msl_anom_hpa': _require('msl_anom')     * SLP_SCALE,
        # AFC at 250 hPa: W m⁻² (no conversion)
        'afc_250'     : _require('afc_250'),
        # Total wind at 250 hPa: m s⁻¹ (rows c/d and e/f)
        'u_250'       : _require('u_250'),
        'v_250'       : _require('v_250'),
        # Total wind at 850 hPa: m s⁻¹
        'u_850'       : _require('u_850'),
        'v_850'       : _require('v_850'),
        # RK criterion at 250 hPa: m⁻¹ s⁻¹ (SI, for sign-reversal mask only)
        'rk_criterion': _require('rk_criterion_250'),
        # Grid
        'x'      : x,
        'y'      : y,
        'x_2d'   : x_2d,
        'y_2d'   : y_2d,
        'n_cases': n_cases,
    }
    ds.close()
    return data


# ============================================================================
# HATCHING MASK: RK MERIDIONAL SIGN-REVERSAL
# ============================================================================

def meridional_sign_reversal_mask(field, half_window=1):
    """
    Boolean mask: True where the field has a meridional sign reversal within
    a ±half_window-point neighbourhood along the y (latitude) axis.

    Definition
    ----------
    For each point (i, j):

        mask[i, j] = True  iff
            nanmin( field[i-w : i+w+1, j] ) < 0
            AND
            nanmax( field[i-w : i+w+1, j] ) > 0

        where w = half_window.

    Boundary treatment: the window is truncated at the domain edges
    (no wrap-around); nan values are ignored by nanmin/nanmax.
    Zero values (rk ≡ 0 exactly) are NOT considered sign reversals
    (strict inequalities).

    Physical justification (applied to rk_criterion_250 = ∂η/∂y @ 250 hPa):
      The Rayleigh-Kuo necessary condition for barotropic instability
      requires ∂η/∂y to change sign somewhere in the meridional domain
      (Rayleigh 1880; Kuo 1949; Charney & Stern 1962).  This mask
      identifies the zero-crossing *band* of ∂η/∂y along y, i.e., the
      transition zone between positive and negative ∂η/∂y.  Hatching this
      region highlights where the necessary condition is *locally* met —
      not merely where rk < 0 point-by-point.

    Parameters
    ----------
    field : np.ndarray, shape (ny, nx)
    half_window : int ≥ 1

    Returns
    -------
    mask : np.ndarray of bool, shape (ny, nx)
    """
    ny, nx = field.shape
    mask = np.zeros((ny, nx), dtype=bool)
    for i in range(ny):
        i0 = max(0, i - half_window)
        i1 = min(ny, i + half_window + 1)
        window  = field[i0:i1, :]
        col_min = np.nanmin(window, axis=0)
        col_max = np.nanmax(window, axis=0)
        mask[i, :] = (col_min < 0.0) & (col_max > 0.0)
    return mask


# ============================================================================
# AXIS HELPERS
# ============================================================================

def _ax_setup(ax, x, y, show_xlabels=False, show_ylabels=False):
    """Square axes with storm-relative extent, no tick labels by default."""
    ax.set_xlim(x.min(), x.max())
    ax.set_ylim(y.min(), y.max())
    try:
        ax.set_box_aspect(1)
    except AttributeError:
        ax.set_aspect('equal')
    ax.tick_params(length=3)
    if show_xlabels:
        xticks = np.arange(-15, 16, 5)
        ax.set_xticks(xticks)
        ax.set_xticklabels([f'{v:+d}°' for v in xticks],
                            fontsize=TICK_LABELSIZE - 1)
    else:
        ax.set_xticklabels([])
    if show_ylabels:
        yticks = np.arange(-15, 16, 5)
        ax.set_yticks(yticks)
        ax.set_yticklabels([f'{v:+d}°' for v in yticks],
                            fontsize=TICK_LABELSIZE - 1)
    else:
        ax.set_yticklabels([])


def _add_slp_contours(ax, x_2d, y_2d, msl_hpa):
    """
    Thin, semi-transparent SLP contours at SLP_INTERVAL spacing.
    Serve as spatial reference for cyclone position — not a primary element.
    """
    slp_min = np.floor(np.nanmin(msl_hpa) / SLP_INTERVAL) * SLP_INTERVAL
    slp_max = np.ceil(np.nanmax(msl_hpa)  / SLP_INTERVAL) * SLP_INTERVAL
    levels = np.arange(slp_min, slp_max + SLP_INTERVAL, SLP_INTERVAL)
    if len(levels) > 1:
        ax.contour(x_2d, y_2d, msl_hpa, levels=levels,
                   colors='k', linewidths=0.45, alpha=0.40, zorder=4)


def _add_wind_vectors(ax, x_2d, y_2d, u, v, scale, key_u, key_label,
                      add_key=False, speed_threshold=None):
    """
    Subsampled wind vector overlay.

    Parameters
    ----------
    add_key         : bool   draw quiver key in top-right corner of panel
    speed_threshold : float or None
        If set, only plot vectors where sqrt(u²+v²) >= speed_threshold.
        Sub-threshold grid points are masked (set to NaN) before quiver.
    """
    sk = VECTOR_SKIP
    u_plot = u[::sk, ::sk].copy()
    v_plot = v[::sk, ::sk].copy()

    if speed_threshold is not None:
        speed = np.sqrt(u_plot**2 + v_plot**2)
        mask  = speed < speed_threshold
        u_plot = np.where(mask, np.nan, u_plot)
        v_plot = np.where(mask, np.nan, v_plot)

    Q = ax.quiver(
        x_2d[::sk, ::sk], y_2d[::sk, ::sk],
        u_plot, v_plot,
        scale=scale, width=0.004, color='gray',
        headwidth=3, headlength=4, headaxislength=3.5,
        zorder=8,
    )
    if add_key:
        ax.quiverkey(Q, X=0.97, Y=0.95, U=key_u,
                     label=f'{key_u:.0f} m s$^{{-1}}$',
                     labelpos='W', fontproperties={'size': 10}, zorder=12)
    return Q


def _add_lec_box(ax):
    """
    Dashed 15°×15° rectangle centred at (0, 0) representing the LEC
    computation domain used to derive energy conversion terms.
    """
    rect = Rectangle((-7.5, -7.5), 15.0, 15.0,
                     linewidth=1.2, edgecolor='k', facecolor='none',
                     linestyle='--', zorder=9)
    ax.add_patch(rect)


def _mark_center(ax):
    """Cyclone-centre marker at (0, 0)."""
    ax.plot(0, 0, 'k*', markersize=12,
            markeredgecolor='white', markeredgewidth=1.2, zorder=10)


def _panel_label(ax, label):
    """Bold panel label (e.g., '(a)') at upper-left corner."""
    ax.text(0.01, 0.98, label,
            transform=ax.transAxes,
            fontsize=ANNOTATION_FONTSIZE, fontweight='bold',
            ha='left', va='top', zorder=11)


def _add_colorbar(fig, gs_cell, im, label):
    """Add a right-side colorbar in the dedicated GridSpec column."""
    cax = fig.add_subplot(gs_cell)
    cb  = plt.colorbar(im, cax=cax)
    cb.set_label(label, fontsize=CBAR_LABELSIZE)
    cb.ax.tick_params(labelsize=CBAR_LABELSIZE)
    cax.yaxis.set_ticks_position('right')
    return cb


# ============================================================================
# FIGURE CREATION
# ============================================================================

def create_figure(ep_data, output_png):
    """
    Create Figure 8: 3×2 EP1 vs EP2 dynamical composites.

    Colormap limits are computed *globally* across both EPs for each row,
    ensuring the shading scales are identical between the two columns and
    differences are directly readable.

    Parameters
    ----------
    ep_data    : dict {'EP1': data_dict, 'EP2': data_dict}
    output_png : Path
    """
    eps = ['EP1', 'EP2']

    # ── Global symmetric colormap limits ──────────────────────────────────────
    def _sym_lim(key):
        return max(np.nanmax(np.abs(ep_data[ep][key])) for ep in eps)

    lim_pv200 = _sym_lim('pv_200_anom')    # PVU
    lim_pv850 = _sym_lim('pv_850_anom')    # PVU
    lim_afc   = _sym_lim('afc_250')        # W m⁻²

    levels_pv200 = np.linspace(-lim_pv200, lim_pv200, 21)
    levels_pv850 = np.linspace(-lim_pv850, lim_pv850, 21)
    levels_afc   = np.linspace(-lim_afc,   lim_afc,   21)

    # ── GridSpec: 3 rows × 3 cols  (EP1 | EP2 | colorbar) ────────────────────
    fig = plt.figure(figsize=FIGSIZE)
    gs = gridspec.GridSpec(
        3, 3,
        width_ratios=[1, 1, 0.055],
        hspace=0.07,
        wspace=0.07,
        left=0.05, right=0.94, top=0.95, bottom=0.04,
    )

    panel_labels = [['(a)', '(b)'], ['(c)', '(d)'], ['(e)', '(f)']]

    # =========================================================================
    # ROW 0 — Upper-level forcing / baroclinic environment
    # Shading : pv_200_anom [PVU]
    # Contours: egr ≥ 0.5 day⁻¹
    # Vectors : total wind at 250 hPa [m s⁻¹]
    # Thin ctr: SLP [hPa]
    # =========================================================================
    print("  Row 1: pv_200_anom + EGR (≥0.5) + wind250 + SLP ...", flush=True)
    im_r0 = None
    for col, ep in enumerate(eps):
        d  = ep_data[ep]
        ax = fig.add_subplot(gs[0, col])

        im = ax.contourf(d['x_2d'], d['y_2d'], d['pv_200_anom'],
                         levels=levels_pv200, cmap=CMAP_PV200_ANOM, extend='both')
        if col == 0:
            im_r0 = im

        # EGR contours — only levels ≥ 0.5 day⁻¹, no inline labels
        egr_valid = EGR_CONTOUR_LEVELS[
            (EGR_CONTOUR_LEVELS >= np.nanmin(d['egr'])) &
            (EGR_CONTOUR_LEVELS <= np.nanmax(d['egr']))
        ]
        if len(egr_valid):
            ax.contour(d['x_2d'], d['y_2d'], d['egr'],
                       levels=egr_valid,
                       colors='k', linewidths=1.1, alpha=0.85, zorder=5)

        # SLP anomaly contours (thin reference)
        _add_slp_contours(ax, d['x_2d'], d['y_2d'], d['msl_anom_hpa'])
        _add_lec_box(ax)
        _mark_center(ax)
        _ax_setup(ax, d['x'], d['y'], show_ylabels=(col == 0))
        _panel_label(ax, panel_labels[0][col])

        # Column headers: only EP label, no n_cases
        ax.set_title(ep, fontsize=PANEL_TITLESIZE, fontweight='bold', pad=4)

    _add_colorbar(fig, gs[0, 2], im_r0, r"PV$_{200}$ anom (PVU)")

    # =========================================================================
    # ROW 1 — Low-level frontal / diabatic response
    # Shading : pv_850_anom     [PVU]
    # Contours: adv_T_850 total [K h⁻¹]  — negative=dashed blue, positive=solid red
    # Vectors : total wind at 850 hPa [m s⁻¹]
    # Thin ctr: SLP [hPa]
    # =========================================================================
    print("  Row 2: pv_850_anom + T-adv total + wind850 + SLP ...", flush=True)
    im_r1 = None
    for col, ep in enumerate(eps):
        d  = ep_data[ep]
        ax = fig.add_subplot(gs[1, col])

        im = ax.contourf(d['x_2d'], d['y_2d'], d['pv_850_anom'],
                         levels=levels_pv850, cmap=CMAP_PV850_ANOM, extend='both')
        if col == 0:
            im_r1 = im

        tadv = d['adv_T_850']

        # Cold-advection contours (negative): dashed blue
        neg_valid = TADV_NEG_LEVELS[TADV_NEG_LEVELS >= np.nanmin(tadv)]
        if len(neg_valid):
            ax.contour(d['x_2d'], d['y_2d'], tadv,
                       levels=neg_valid,
                       colors='steelblue', linewidths=1.8,
                       linestyles='dashed', alpha=0.9, zorder=5)

        # Warm-advection contours (positive): solid red
        pos_valid = TADV_POS_LEVELS[TADV_POS_LEVELS <= np.nanmax(tadv)]
        if len(pos_valid):
            ax.contour(d['x_2d'], d['y_2d'], tadv,
                       levels=pos_valid,
                       colors='firebrick', linewidths=1.8,
                       linestyles='solid', alpha=0.9, zorder=5)

        # Total wind vectors at 850 hPa
        _add_wind_vectors(ax, d['x_2d'], d['y_2d'], d['u_850'], d['v_850'],
                          scale=VECTOR_SCALE_850, key_u=QUIVER_KEY_U_850,
                          key_label='850 hPa', add_key=(col == 1))

        _add_slp_contours(ax, d['x_2d'], d['y_2d'], d['msl_hpa'])
        _add_lec_box(ax)
        _mark_center(ax)
        _ax_setup(ax, d['x'], d['y'], show_ylabels=(col == 0))
        _panel_label(ax, panel_labels[1][col])

    _add_colorbar(fig, gs[1, 2], im_r1, r"PV$_{850}$ anom (PVU)")

    # =========================================================================
    # ROW 2 — Jet-level energetics / barotropic favorability
    # Shading : afc_250      [W m⁻²]
    # Vectors : total wind at 250 hPa [m s⁻¹]
    # Hatching: RK meridional sign-reversal mask
    # =========================================================================
    print("  Row 3: AFC + total wind 250 + RK hatching ...", flush=True)
    im_r2 = None
    for col, ep in enumerate(eps):
        d  = ep_data[ep]
        ax = fig.add_subplot(gs[2, col])

        im = ax.contourf(d['x_2d'], d['y_2d'], d['afc_250'],
                         levels=levels_afc, cmap=CMAP_AFC, extend='both')
        if col == 0:
            im_r2 = im

        # ── RK meridional sign-reversal hatching ─────────────────────────────
        rk_mask = meridional_sign_reversal_mask(d['rk_criterion'],
                                                half_window=RK_HATCH_HALF_WINDOW)
        hatch_field = rk_mask.astype(float)  # 0 outside, 1 inside transition band

        with mpl.rc_context({'hatch.color': HATCH_COLOR,
                              'hatch.linewidth': HATCH_LW}):
            ax.contourf(d['x_2d'], d['y_2d'], hatch_field,
                        levels=[0.5, 1.5],
                        colors=['none'],
                        hatches=[HATCH_PATTERN],
                        zorder=6)

        # Total wind vectors at 250 hPa — only where speed ≥ 30 m/s
        _add_wind_vectors(ax, d['x_2d'], d['y_2d'], d['u_250'], d['v_250'],
                          scale=VECTOR_SCALE_250, key_u=QUIVER_KEY_U_250,
                          key_label='250 hPa', add_key=(col == 1),
                          speed_threshold=30.0)

        _add_slp_contours(ax, d['x_2d'], d['y_2d'], d['msl_hpa'])
        _add_lec_box(ax)
        _mark_center(ax)
        _ax_setup(ax, d['x'], d['y'],
                  show_xlabels=True, show_ylabels=(col == 0))
        _panel_label(ax, panel_labels[2][col])

    _add_colorbar(fig, gs[2, 2], im_r2, r"AFC$_{250}$ (W m$^{-2}$)")

    # ── Save ─────────────────────────────────────────────────────────────────
    plt.savefig(output_png, dpi=DPI, bbox_inches='tight')
    print(f"  Saved: {output_png}", flush=True)
    plt.close()


# ============================================================================
# MAIN
# ============================================================================

def main():
    """Generate Figure 8: EP1 vs EP2 dynamical composites (3×2)."""
    print("=" * 80)
    print("FIGURE 8 — EP1 vs EP2 DYNAMICAL COMPOSITES (3×2)")
    print("=" * 80)

    # ── Verify input files ───────────────────────────────────────────────────
    missing = [ep for ep, f in COMPOSITE_FILES.items() if not f.exists()]
    if missing:
        print(f"\nERROR: Composite files not found for: {missing}")
        print("  Run: python scripts/ep_structure_analysis/step3_precompute_composites.py")
        return 1

    # ── Load composites ───────────────────────────────────────────────────────
    ep_data = {}
    for ep in ['EP1', 'EP2']:
        print(f"\nLoading {ep} composite ...")
        ep_data[ep] = load_ep_composite(ep)
        d = ep_data[ep]
        print(f"  n_cases      = {d['n_cases']}")
        print(f"  domain       = ({d['x'].min():.1f}, {d['x'].max():.1f})°  ×"
              f"  ({d['y'].min():.1f}, {d['y'].max():.1f})°")
        print(f"  pv_200_anom  [{d['pv_200_anom'].min():.3f}, "
              f"{d['pv_200_anom'].max():.3f}] PVU")
        print(f"  pv_850_anom  [{d['pv_850_anom'].min():.4f}, "
              f"{d['pv_850_anom'].max():.4f}] PVU")
        print(f"  egr          [{d['egr'].min():.3f}, "
              f"{d['egr'].max():.3f}] day⁻¹")
        print(f"  adv_T_850    [{d['adv_T_850'].min():.4f}, "
              f"{d['adv_T_850'].max():.4f}] K h⁻¹")
        print(f"  afc_250      [{d['afc_250'].min():.5f}, "
              f"{d['afc_250'].max():.5f}] W m⁻²")
        rk_mask = meridional_sign_reversal_mask(d['rk_criterion'],
                                                half_window=RK_HATCH_HALF_WINDOW)
        coverage = rk_mask.sum() / rk_mask.size * 100
        print(f"  RK sign-reversal mask coverage: {coverage:.1f}% of domain")

    print(f"\n{'='*80}")
    print("Creating figure ...")
    print(f"{'='*80}\n")

    create_figure(ep_data, OUTPUT_PNG)

    print(f"\n{'='*80}")
    print("Figure 8 complete!")
    print(f"  PNG : {OUTPUT_PNG}")
    print(f"{'='*80}\n")
    return 0


if __name__ == '__main__':
    sys.exit(main())
