import type { Metadata } from 'next'
import Breadcrumbs from '@/components/layout/Breadcrumbs'
import AnalysisHero from '@/components/analysis/AnalysisHero'
import ResultSummaryCallout from '@/components/analysis/ResultSummaryCallout'
import FigurePanel from '@/components/analysis/FigurePanel'
import StatsTable from '@/components/analysis/StatsTable'
import { figureUrl } from '@/lib/utils'
import manifestData from '@/content/cps_manifest.json'

export const metadata: Metadata = {
  title: 'Cyclone Phase Space — Thermal Structure of the Energy Patterns',
  description:
    'Hart (2003) cyclone phase space applied to 6,776 South Atlantic cyclones, classified into extratropical, subtropical and tropical structure under a 36 h persistence gate, and cross-referenced against the Energy Patterns.',
}

type Manifest = typeof manifestData
const manifest = manifestData as Manifest

const fig = (key: keyof Manifest['figures']) => figureUrl(manifest.figures[key])

/** Rows of the EP-relative table for one outcome. */
function relFor(outcome: string) {
  return manifest.ep_relative.filter((r) => r.outcome === outcome)
}

function pFormat(p: number): string {
  if (p >= 0.01) return p.toFixed(3)
  return p.toExponential(1).replace('e-', ' × 10⁻').replace(/⁻(\d+)/, (_, d) =>
    '⁻' + String(d).split('').map((c) => '⁰¹²³⁴⁵⁶⁷⁸⁹'[Number(c)]).join('')
  )
}

export default function CpsPage() {
  const pop = manifest.population
  const crit = manifest.criteria
  const named = manifest.classes.filter((c) => c.kind === 'single_state' || c.kind === 'transition')
  const stRows = relFor('ST')
  const headline = stRows.find((r) => r.significant_holm)

  return (
    <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
      <Breadcrumbs />
      <AnalysisHero
        title="Cyclone Phase Space"
        subtitle="Thermal structure of the Energy Patterns"
        badge="CPS · Hart (2003)"
        description={`Every one of the ${pop.catalogue.toLocaleString()} tracked cyclones is placed in the Hart (2003) cyclone phase space at ${pop.timestep_hours}-hourly resolution and classified as extratropical, subtropical or tropical, subject to a ${crit.persistence_hours} h persistence requirement. The resulting classes are cross-referenced against the three Energy Patterns to ask whether a cyclone's energetics relate to its thermal structure. Genesis ${pop.genesis_first} to ${pop.genesis_last}.`}
      />

      <div className="space-y-12">
        {/* ---------------- Headline ---------------- */}
        <ResultSummaryCallout type="result" title="Main result">
          <p>
            The Energy Patterns differ in whether a cyclone <em>becomes</em> subtropical,
            not in whether it <em>is</em> subtropical. EP2 shows{' '}
            <strong>{headline ? headline.ratio.toFixed(2) : '1.36'}×</strong> the pooled
            rate of subtropical transition (
            {headline ? `${headline.rate_pct}% against ${headline.epall_rate_pct}%` : ''},
            Fisher OR {headline?.odds_ratio}, p = {headline ? pFormat(headline.p) : ''}),
            the only one of nine contrasts that survives Holm correction. The
            single-state subtropical class shows no EP dependence at all — its three
            ratios span {Math.min(...relFor('SC').map((r) => r.ratio)).toFixed(2)}–
            {Math.max(...relFor('SC').map((r) => r.ratio)).toFixed(2)}, well inside each
            other&apos;s confidence intervals.
          </p>
        </ResultSummaryCallout>

        {/* ---------------- Provenance ---------------- */}
        <section>
          <h2 className="mb-3 text-lg font-bold text-slate-900">Provenance</h2>
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm leading-relaxed text-slate-700">
            <p>
              The per-cyclone CPS parameters were computed by{' '}
              <strong>{manifest.provenance.cps_computed_by}</strong>. {manifest.provenance.note}
            </p>
            <p className="mt-2 text-xs text-slate-500">
              Calculator preserved unmodified at{' '}
              <code className="rounded bg-white px-1 border border-amber-200">
                {manifest.provenance.calculator}
              </code>
              . Everything downstream is regenerated by{' '}
              <code className="rounded bg-white px-1 border border-amber-200">
                {manifest.generated_from}
              </code>
              .
            </p>
          </div>
        </section>

        {/* ---------------- How to read the diagrams ---------------- */}
        <section>
          <h2 className="mb-3 text-lg font-bold text-slate-900">How to read the diagrams</h2>
          <p className="mb-4 text-sm leading-relaxed text-slate-600">
            The phase space has three parameters: <strong>B</strong>, the storm-motion-relative
            900–600 hPa thickness asymmetry (frontal versus symmetric structure), and the
            lower and upper thermal winds <strong>−V<sub>T</sub><sup>L</sup></strong>{' '}
            (900–600 hPa) and <strong>−V<sub>T</sub><sup>U</sup></strong> (600–300 hPa),
            positive for a warm core. Each panel of every diagram is a two-dimensional slice
            of that three-dimensional space, so the shaded regions are the projection of each
            class with the third parameter left free.
          </p>

          <div className="mb-5 grid gap-3 sm:grid-cols-3">
            {crit.classes.map((c) => (
              <div
                key={c.code}
                className="rounded-xl border-2 bg-white p-4"
                style={{ borderColor: c.color + '55' }}
              >
                <div className="flex items-center gap-2">
                  <span
                    className="flex h-7 w-7 items-center justify-center rounded-lg text-xs font-bold text-white"
                    style={{ backgroundColor: c.color }}
                  >
                    {c.code}
                  </span>
                  <span className="text-sm font-semibold capitalize text-slate-900">{c.name}</span>
                </div>
                <ul className="mt-3 space-y-0.5 font-mono text-xs text-slate-600">
                  {c.terms.map((t) => (
                    <li key={t}>{t}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <FigurePanel
            src={fig('reference')}
            alt="Reference diagram of the canonical cyclone phase space class regions"
            caption={`Schematic of the class regions, carrying no data. Grey marks where more than one class can claim a point — a real property of the definitions, where the timestep precedence (${crit.precedence.join(' > ')}) decides. Blank corners belong to no cyclone type.`}
            source="scripts/cps_analysis/make_reference_diagram.py"
          />
        </section>

        {/* ---------------- Protocol ---------------- */}
        <section>
          <h2 className="mb-3 text-lg font-bold text-slate-900">Classification protocol</h2>
          <div className="space-y-3 rounded-xl border border-slate-200 bg-white p-5 text-sm leading-relaxed text-slate-600">
            <p>
              <strong>Thresholds.</strong> {crit.source}. A timestep satisfying more than one
              class specification is resolved by precedence: {crit.precedence.join(' > ')}.
            </p>
            <p>
              <strong>Persistence gate.</strong> A cyclone is only <em>identified</em> as a
              class when it holds that structure for <strong>{crit.persistence_hours} consecutive
              hours</strong> — Guishard et al. (2009), &ldquo;more than one diurnal cycle&rdquo;,
              adopted for the South Atlantic by Gozzo et al. (2014). The CPS parameters are used
              unsmoothed; the literature that this protocol follows controls short-term noise
              through persistence rather than through a running mean.
            </p>
            <p>
              <strong>Warm-seclusion filter.</strong> The phase space alone cannot separate a
              tropical cyclone from a Shapiro–Keyser warm seclusion: the occlusion sequence
              passes through hybrid and then symmetric warm-core structure, and it does so for
              well over {crit.persistence_hours} h. A persistent warm core is therefore only
              accepted as tropical when the run sits equatorward of{' '}
              {Math.abs(crit.tt_max_poleward_lat)}°S and spends at least{' '}
              {Math.round(crit.tt_min_ocean_fraction * 100)}% of its time over ocean. In this
              population the filter rejected{' '}
              <strong>{manifest.rejected_by_tt_test.warm_seclusion} warm seclusions</strong> and{' '}
              {manifest.rejected_by_tt_test.indeterminate_warm_core} indeterminate warm cores.
            </p>
            <p>
              <strong>Characteristic classes.</strong> A cyclone that never sustains a structure
              for {crit.persistence_hours} h is not structureless. When one structure dominates
              at least {Math.round(crit.min_dominance * 100)}% of its classifiable timesteps it
              is labelled <code className="rounded bg-slate-100 px-1">*_like</code> — a statement
              about <em>characteristics</em>, not an identification. The literature threshold is
              left untouched for the named classes.
            </p>
          </div>
        </section>

        {/* ---------------- Class composition ---------------- */}
        <section>
          <h2 className="mb-4 text-lg font-bold text-slate-900">
            Classification of the {pop.catalogue.toLocaleString()} cyclones
          </h2>

          <div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {named
              .filter((c) => c.n > 0)
              .map((c) => (
                <div key={c.code} className="rounded-xl border border-slate-200 bg-white p-4">
                  <div className="flex items-center justify-between">
                    <span
                      className="rounded-md px-2 py-0.5 text-xs font-bold text-white"
                      style={{ backgroundColor: c.color }}
                    >
                      {c.code}
                    </span>
                    <span className="text-xs text-slate-400">{c.pct}%</span>
                  </div>
                  <p className="mt-2 text-2xl font-bold text-slate-900">{c.n.toLocaleString()}</p>
                  <p className="mt-1 text-xs leading-relaxed text-slate-500">{c.label}</p>
                </div>
              ))}
          </div>

          <StatsTable
            title="Full classification"
            columns={[
              { key: 'code', label: 'Class' },
              { key: 'label', label: 'Meaning' },
              { key: 'n', label: 'n', align: 'right' },
              { key: 'pct', label: '%', align: 'right' },
            ]}
            rows={manifest.classes.map((c) => ({
              code: c.code,
              label: c.label,
              n: c.n.toLocaleString(),
              pct: c.pct.toFixed(1),
            }))}
            caption={`TT (tropical transition) and ET (extratropical transition, TC → EC in the strict sense of Evans and Hart 2003) are empty by construction: the genesis boxes of this catalogue exclude every documented South Atlantic tropical system, so there is no tropical cyclone to transition from or to. The *_like classes describe characteristics that never reached the ${crit.persistence_hours} h gate.`}
          />

          <div className="mt-5">
            <FigurePanel
              src={fig('composition')}
              alt="Phase-class composition of each Energy Pattern"
              caption="Left: phase-class composition of each Energy Pattern. Right: the transition classes alone, which are the scientifically interesting part and invisible in the stacked bars."
              source="scripts/cps_analysis/step4_phase_figures.py"
            />
          </div>
        </section>

        {/* ---------------- Headline figure ---------------- */}
        <section>
          <h2 className="mb-4 text-lg font-bold text-slate-900">
            Subtropical structure by Energy Pattern
          </h2>
          <FigurePanel
            src={fig('ep_relative')}
            alt="Subtropical frequency of each Energy Pattern relative to the pooled population"
            caption={`(a) Frequency within each Energy Pattern with Wilson 95% intervals, against the pooled EPALL reference. (b) The same expressed as a ratio to EPALL, on a log scale. EPALL is the union EP1 + EP2 + EP3 = ${pop.ep_labelled.toLocaleString()} cyclones — not the full catalogue, since only clustered cyclones carry an Energy Pattern. Because each EP is nested in that reference, the ratio is a descriptive effect size; significance comes from Fisher's exact test of each EP against the other two pooled, Holm-corrected over the nine contrasts.`}
            source="scripts/cps_analysis/step8_ep_relative_frequency.py"
          />

          <div className="mt-5">
            <StatsTable
              title="Subtropical transition (ST) — each EP against the other two pooled"
              columns={[
                { key: 'ep', label: 'EP' },
                { key: 'rate', label: 'rate', align: 'right' },
                { key: 'ci', label: '95% CI', align: 'center' },
                { key: 'ratio', label: '×EPALL', align: 'right' },
                { key: 'or', label: 'OR', align: 'right' },
                { key: 'p', label: 'p', align: 'right' },
                { key: 'holm', label: 'Holm', align: 'center' },
              ]}
              rows={stRows.map((r) => ({
                ep: r.ep,
                rate: `${r.rate_pct}% (${r.k}/${r.n})`,
                ci: `${r.rate_lo_pct}–${r.rate_hi_pct}%`,
                ratio: r.ratio.toFixed(2),
                or: r.odds_ratio.toFixed(2),
                p: pFormat(r.p),
                holm: r.significant_holm ? '✓ survives' : '—',
              }))}
              caption={`EPALL rate ${stRows[0]?.epall_rate_pct}%. Only EP2 survives Holm correction over the nine contrasts tested; the EP3 depletion is nominally significant only and must not be reported as established.`}
            />
          </div>
        </section>

        {/* ---------------- Phase space occupancy ---------------- */}
        <section>
          <h2 className="mb-4 text-lg font-bold text-slate-900">Where each Energy Pattern sits</h2>
          <FigurePanel
            src={fig('phase_space_by_ep')}
            alt="Cyclone phase space diagrams for EPALL and each Energy Pattern"
            caption="Every classifiable timestep, as a density of the fraction of each column's timesteps per bin on a shared logarithmic scale, so the columns compare directly despite very unequal sample sizes. Top row: B against the lower thermal wind. Bottom row: upper against lower thermal wind."
            source="scripts/cps_analysis/step5_phase_space_figures.py"
          />
          <div className="mt-5">
            <FigurePanel
              src={fig('single_state_sc')}
              alt="Cyclone phase space restricted to the single-state subtropical cyclones"
              caption="Restricted to the cyclones whose only persistent state is subtropical. The density shows only their subtropical-classified timesteps; the grey dots are the rest of their life. Plotting all their timesteps would reproduce something close to the whole-population cloud and hide the classification — these cyclones spend a large part of their life in other structures, just never for 36 consecutive hours."
              source="scripts/cps_analysis/step5_phase_space_figures.py"
            />
          </div>
        </section>

        {/* ---------------- Transitions ---------------- */}
        <section>
          <h2 className="mb-4 text-lg font-bold text-slate-900">What a transition looks like</h2>
          <FigurePanel
            src={fig('trajectories')}
            alt="Phase-space trajectories of the transitioning cyclones"
            caption="Each marker is one 3-hourly timestep, coloured by the structure it holds at that moment; lines connect a cyclone's successive timesteps. The convention of the case-study literature, applied to a whole class at once so the shape of a transition can be read as a population. ST is the extratropical-to-subtropical pathway, SD its reverse."
            source="scripts/cps_analysis/step6_transition_trajectories.py"
          />
          <div className="mt-5">
            <FigurePanel
              src={fig('transitions')}
              alt="Where subtropical structure appears in the life cycle, how long it lasts, and when in the year"
              caption="Timing is expressed in life-cycle phase rather than hours from genesis: the phases come from the project's own vorticity-based segmentation, independent of the CPS, and they normalise for very unequal cyclone lifetimes."
              source="scripts/cps_analysis/step4_phase_figures.py"
            />
          </div>
        </section>

        {/* ---------------- Warm seclusion filter ---------------- */}
        <section>
          <h2 className="mb-4 text-lg font-bold text-slate-900">The warm-seclusion problem</h2>
          <p className="mb-4 text-sm leading-relaxed text-slate-600">
            This is the step that decides whether the analysis reports tropical cyclones that
            are not there. Persistence alone does not solve it — a warm seclusion routinely
            holds symmetric warm-core structure far beyond the gate. The rejected runs in this
            population sit at 54–68°S, deep in the Southern Ocean, and reach their warm core a
            median 75 h after genesis, at the end of a baroclinic life cycle.
          </p>
          <FigurePanel
            src={fig('tropical_runs')}
            alt="Every persistent tropical run, accepted or rejected by the tropical-transition test"
            caption={`Every persistent tropical run in the catalogue. The shaded band is where a warm core is accepted as tropical (equatorward of ${Math.abs(crit.tt_max_poleward_lat)}°S). The equatorward bound is deliberately absent: Iba, the first documented pure tropical cyclogenesis in the western South Atlantic, formed at about 20°S, and a system further equatorward is more plausible as tropical, not less.`}
            source="scripts/cps_analysis/step4_phase_figures.py"
          />
        </section>

        {/* ---------------- Caveats ---------------- */}
        <section>
          <h2 className="mb-3 text-lg font-bold text-slate-900">Caveats</h2>
          <ResultSummaryCallout type="warning" title="Read before quoting any number here">
            <ul className="list-disc space-y-2 pl-4 text-sm">
              <li>
                <strong>The two TC cyclones are candidates, not identifications.</strong> They
                have shallow warm cores and have not been inspected case by case. Do not report
                them as identified South Atlantic tropical cyclones.
              </li>
              <li>
                <strong>TT and ET are empty by construction.</strong> Catarina, Anita, Arani,
                Deni, Guará and Iba all form outside this catalogue&apos;s genesis boxes; Raoni,
                Yakecan, Akará and Biguá postdate the record. This is a property of the
                population, not a failure of the method.
              </li>
              <li>
                <strong>The subtropical count is threshold-sensitive by a factor of 6–8</strong>{' '}
                across the six threshold sets tested, at every level of strictness. Any
                subtropical number must be quoted with its threshold set attached.
              </li>
              <li>
                <strong>Multiple comparisons matter here.</strong> Nine contrasts were tested.
                Only EP2 × ST survives Holm correction; the other two nominally significant
                results do not.
              </li>
              <li>
                <strong>The 500 km CPS radius may not represent small, shallow systems well</strong>{' '}
                — a caveat Conrado et al. (2024) raise about their own work — and 13 cyclones
                (0.2%) have no CPS series at all.
              </li>
            </ul>
          </ResultSummaryCallout>
        </section>

        {/* ---------------- Validation status ---------------- */}
        <section>
          <h2 className="mb-3 text-lg font-bold text-slate-900">Validation status</h2>
          <div className="rounded-xl border border-slate-200 bg-white p-5 text-sm leading-relaxed text-slate-600">
            <p>
              A gallery of <strong>{manifest.gallery.n_figures}</strong> single-cyclone phase
              diagrams — one sampled case per class × year of genesis × genesis region, across{' '}
              {manifest.gallery.n_classes} classes — is generated for case-by-case visual
              validation, the step Gozzo et al. performed manually and this analysis has not yet
              completed. It lives in the repository rather than on this site.
            </p>
            <p className="mt-2">
              Two independent checks against the literature do pass: the relaxed protocol gives
              9.3 subtropical cyclones per year against Gozzo et al.&apos;s 7.2, and the strict
              Guishard threshold set gives 1.8 per year against Evans and Braun&apos;s 1.2, with
              the DJF maximum reproduced in both. The named South Atlantic subtropical cyclones
              Bapo and Cari are both classified subtropical.
            </p>
          </div>
        </section>

        {/* ---------------- Sources ---------------- */}
        <ResultSummaryCallout type="info" title="Scripts and outputs">
          <ul className="space-y-1 text-sm">
            <li>
              <strong>Pipeline:</strong>{' '}
              <code className="rounded bg-slate-100 px-1">scripts/cps_analysis/</code> — reference
              diagram plus steps 1–8, run by{' '}
              <code className="rounded bg-slate-100 px-1">run_all.py</code>
            </li>
            <li>
              <strong>Thresholds, gates and colours:</strong>{' '}
              <code className="rounded bg-slate-100 px-1">scripts/cps_analysis/cps_criteria.py</code>{' '}
              — the single source of truth, with the source quote for every threshold set
            </li>
            <li>
              <strong>Science record:</strong>{' '}
              <code className="rounded bg-slate-100 px-1">scripts/cps_analysis/SCIENTIFIC_NOTES.md</code>{' '}
              (canonical) and{' '}
              <code className="rounded bg-slate-100 px-1">scripts/cps_analysis/sensitivity/</code>{' '}
              (the six threshold sets tested, kept as a record of what motivated the canonical design)
            </li>
            <li>
              <strong>Per-cyclone lists:</strong>{' '}
              <code className="rounded bg-slate-100 px-1">results/cps_analysis/cyclone_lists_by_class.csv</code>
            </li>
            <li>
              <strong>This page:</strong> every number is read from{' '}
              <code className="rounded bg-slate-100 px-1">web/src/content/cps_manifest.json</code>,
              regenerated by{' '}
              <code className="rounded bg-slate-100 px-1">scripts/web/extract_cps_site_data.py</code>
            </li>
          </ul>
        </ResultSummaryCallout>
      </div>
    </div>
  )
}
