#!/usr/bin/env python3
"""
Upload generated figures to Supabase Storage.

This script is a SYNC/UPLOAD utility — it does NOT generate figures.
It takes the outputs already produced by the scientific pipeline and makes
them available for the web application via Supabase Storage public URLs.

Scientific pipeline → local figures/ → this script → Supabase Storage → web site

Prerequisites
-------------
1. Figures must already exist locally (run the scientific pipeline first):
     python scripts/ep_structure_analysis/step4_create_figures.py
     python scripts/cluster_analysis_energy_patterns/run_pipeline.py   # (or relevant scripts)

2. Create the Supabase Storage bucket 'figures' (public) in your Supabase project.
   See web/DEPLOYMENT.md for full instructions.

3. Set environment variables:
     SUPABASE_URL=https://<project-ref>.supabase.co
     SUPABASE_SERVICE_ROLE_KEY=<your-service-role-key>
   The service role key (not anon key) is required to write to Storage.

4. Install supabase-py:
     pip install supabase

Usage
-----
    # Upload everything (dry run first to preview)
    python scripts/web/upload_figures_to_supabase.py --dry-run
    python scripts/web/upload_figures_to_supabase.py

    # Upload only specific directories
    python scripts/web/upload_figures_to_supabase.py --dirs cluster main

    # Force re-upload (overwrite existing)
    python scripts/web/upload_figures_to_supabase.py --overwrite

Bucket structure
----------------
Bucket name : figures   (public, no auth required to read)
Object paths: mirrors the figures/ directory structure in the repo, WITHOUT the
              leading 'figures/' prefix.

  Local path                               → Supabase object key
  figures/cluster/pca_variance_wide.png    → cluster/pca_variance_wide.png
  figures/main/4_lps_combined.png          → main/4_lps_combined.png
  figures/ep_structure/composite_egr.png   → ep_structure/composite_egr.png

Public URL (set as NEXT_PUBLIC_SUPABASE_FIGURES_URL in Vercel):
  https://<project-ref>.supabase.co/storage/v1/object/public/figures

The web app then resolves individual figures as:
  ${NEXT_PUBLIC_SUPABASE_FIGURES_URL}/<object-key>
  e.g. https://<project-ref>.supabase.co/storage/v1/object/public/figures/cluster/pca_variance_wide.png

Author: Danilo Couto de Souza
"""

import argparse
import mimetypes
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
FIGURES_DIR = REPO_ROOT / "figures"
BUCKET_NAME = "figures"

# Directories to upload by default (all that the web site uses)
DEFAULT_DIRS = [
    "cluster",
    "main",
    "ep_structure",   # generated by step4_create_figures.py — may not exist yet
    "ck_subterms",    # generated by scripts/ck_subterms_analysis/step3_validate_and_figures.py
    "cyclone_explorer",  # generated by step6_generate_cyclone_explorer_panels.py
]

# Supported extensions
SUPPORTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".svg", ".gif", ".webp"}


def get_supabase_client():
    """Initialise Supabase client from environment variables."""
    try:
        from supabase import create_client, Client
    except ImportError:
        print("❌ supabase-py not installed. Run: pip install supabase")
        sys.exit(1)

    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

    if not url or not key:
        print("❌ Missing required environment variables:")
        print("   SUPABASE_URL — your Supabase project URL")
        print("   SUPABASE_SERVICE_ROLE_KEY — service role key (Settings → API)")
        print()
        print("   Export them before running:")
        print("   export SUPABASE_URL=https://<project-ref>.supabase.co")
        print("   export SUPABASE_SERVICE_ROLE_KEY=<your-service-role-key>")
        sys.exit(1)

    return create_client(url, key)


def collect_files(dirs: list[str]) -> list[tuple[Path, str]]:
    """Collect (local_path, bucket_object_key) pairs for all figure files.

    Returns pairs where:
      local_path       = absolute path to the file on disk
      bucket_object_key = path within the 'figures' bucket (no leading slash)
    """
    pairs = []
    for dir_name in dirs:
        dir_path = FIGURES_DIR / dir_name
        if not dir_path.exists():
            print(f"  ⚠  {dir_path.relative_to(REPO_ROOT)} — directory not found, skipping")
            continue
        for file_path in sorted(dir_path.rglob("*")):
            if file_path.is_file() and file_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                # Object key = path relative to figures/ (no leading slash)
                object_key = str(file_path.relative_to(FIGURES_DIR))
                pairs.append((file_path, object_key))
    return pairs


def upload_files(
    client,
    pairs: list[tuple[Path, str]],
    overwrite: bool = False,
    dry_run: bool = False,
) -> tuple[int, int, int]:
    """Upload files to Supabase Storage.

    Returns (uploaded, skipped, errors).
    """
    uploaded = skipped = errors = 0

    for local_path, object_key in pairs:
        mime_type, _ = mimetypes.guess_type(str(local_path))
        mime_type = mime_type or "application/octet-stream"

        if dry_run:
            print(f"  [dry-run] {object_key}")
            uploaded += 1
            continue

        try:
            with open(local_path, "rb") as f:
                data = f.read()

            if overwrite:
                # upsert = create or replace
                client.storage.from_(BUCKET_NAME).upload(
                    object_key,
                    data,
                    {"content-type": mime_type, "upsert": "true"},
                )
            else:
                client.storage.from_(BUCKET_NAME).upload(
                    object_key,
                    data,
                    {"content-type": mime_type},
                )

            print(f"  ✓  {object_key}")
            uploaded += 1

        except Exception as e:
            err_str = str(e)
            if "already exists" in err_str or "Duplicate" in err_str:
                print(f"  –  {object_key} (already exists, use --overwrite to replace)")
                skipped += 1
            else:
                print(f"  ✗  {object_key}: {e}")
                errors += 1

    return uploaded, skipped, errors


def print_env_instructions(url: str):
    """Print the Vercel env var to set after upload."""
    base_url = f"{url.rstrip('/')}/storage/v1/object/public/{BUCKET_NAME}"
    print()
    print("=" * 60)
    print("SET THIS ENV VAR IN VERCEL:")
    print("=" * 60)
    print(f"  NEXT_PUBLIC_SUPABASE_FIGURES_URL = {base_url}")
    print()
    print("In Vercel dashboard:")
    print("  Project → Settings → Environment Variables")
    print("  → Add NEXT_PUBLIC_SUPABASE_FIGURES_URL")
    print("  → Redeploy to pick up the change")
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(
        description="Upload figures to Supabase Storage for the web site.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--dirs",
        nargs="+",
        default=DEFAULT_DIRS,
        help=f"Which figure subdirectories to upload (default: {DEFAULT_DIRS})",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing files in the bucket (default: skip existing)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be uploaded without actually uploading",
    )
    args = parser.parse_args()

    print("=" * 60)
    print("UPLOAD FIGURES TO SUPABASE STORAGE")
    print("=" * 60)
    print(f"  Bucket : {BUCKET_NAME}")
    print(f"  Dirs   : {args.dirs}")
    print(f"  Mode   : {'dry-run' if args.dry_run else ('overwrite' if args.overwrite else 'skip existing')}")
    print()

    # Collect files
    print("Collecting files...")
    pairs = collect_files(args.dirs)
    print(f"  Found {len(pairs)} figure files to process")

    if not pairs:
        print("  Nothing to upload.")
        return

    # Connect to Supabase (skip in dry-run)
    if args.dry_run:
        client = None
        supabase_url = os.environ.get("SUPABASE_URL", "<project-ref>")
    else:
        client = get_supabase_client()
        supabase_url = os.environ.get("SUPABASE_URL", "")

    # Upload
    print("\nUploading...")
    uploaded, skipped, errors = upload_files(
        client, pairs, overwrite=args.overwrite, dry_run=args.dry_run
    )

    # Summary
    print()
    print(f"  ✓ Uploaded : {uploaded}")
    print(f"  – Skipped  : {skipped}")
    print(f"  ✗ Errors   : {errors}")

    if not args.dry_run and errors == 0:
        print_env_instructions(supabase_url)


if __name__ == "__main__":
    main()
